contour-terminal/contour

src/terminal/CommandBuilder.cpp, src/terminal/Commands.cpp, src/terminal/Commands.h, src/terminal/Screen.cpp, src/terminal/ScreenBuffer.h, src/terminal_view/DecorationRenderer.cpp, src/terminal_view/DecorationRenderer.h
I've added the feature to render overlines in text. For testing I've been using the following shell command.
`echo -e "The \033[53mtest is\033[55m done"`
=> Feature decorator add overline

src/terminal_view/DecorationRenderer.cpp
I've added the crossed out feature. The only part that was missing was the actual decoration renderer.
Tested using shell command
`echo -e "Hello \e[9mCrossed\e[0m Out"`
=> Add SGR 9, crossed out, decoration renderer.

src/contour/TerminalWidget.cpp
The problem is when the width is near zero then the cell size width will be zero and when that happens there are multible places that can not handle that case.
So to prevent I just have set the minimum Size of the window. 
I don't know it that is the best way to handle the problem, but from my view it is the fastest way to fix it.
Fixes #157.
=> set min Size of window so it does not crash when the width is near zero

src/contour/TerminalWidget.cpp, src/contour/TerminalWidget.h, src/terminal/InputGenerator.cpp, src/terminal/InputGenerator.h, src/terminal/Terminal.cpp, src/terminal/Terminal.h, src/terminal_view/TerminalView.cpp, src/terminal_view/TerminalView.h
Decouples stdin writing from stdout reading in Terminal's stdout handler (that sometimes also writes to stdin that should be handled exclusively in the main thread).
=> Decouple stdin writing thread from stdout reading thread.

cmake/Version.cmake
```
According to [1], string literals in CMake cannot contain '\', they need
to be escaped. Therefore, if we want to pass '\' to string(REGEX), we
need to use '\\'.
[1]: <https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#quoted-argument>
```
=> [cmake] Fix regex escaping in Version.cmake

README.md, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalWidget.cpp, src/contour/main.cpp, src/crispy/CLI.cpp, src/crispy/CLI.h, src/crispy/CLI_test.cpp, src/crispy/CMakeLists.txt
=> new (own) (more flexible) CLI parser

Changelog.md, TODO.md, src/contour/CMakeLists.txt, src/contour/CaptureScreen.cpp, src/contour/CaptureScreen.h, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalWidget.cpp, src/contour/TerminalWidget.h, src/contour/contour.yml, src/contour/main.cpp, src/crispy/utils.h, src/terminal/Functions.h, src/terminal/Grid.cpp, src/terminal/Grid.h, src/terminal/Screen.cpp, src/terminal/Screen.h, src/terminal/ScreenEvents.h, src/terminal/Screen_test.cpp, src/terminal/Sequencer.cpp, src/terminal/Terminal.cpp, src/terminal/Terminal.h, src/terminal/VTType.cpp, src/terminal/VTType.h, src/terminal/pty/UnixPty.cpp, src/terminal_view/TerminalView.cpp, src/terminal_view/TerminalView.h
Implements #168.
```txt
contour capture
Captures the screen buffer of the currently running terminal.
Options:
[logical]        Tells the terminal to use logical lines for counting and capturing.
[timeout FLOAT]  Sets timeout seconds to wait for terminal to respond. [default: 1]
[lines UINT]     The number of lines to capture [default: 0]
output STRING    Output file name to store the screen capture to.
```
This feature is purely VT sequence based, so it also works across remote connections.
```sh
CSI > Pm ;  Pc t
```
* **Pm:** how to count the lines, 0 raw mapping, 1 for logical line mapping (unwrapping wrapped lines into a single logical one).
* **Pc:** the number of lines to capture from the bottom of the main page area, counting upwards, up until the history top is reached. If …
=> Adds screen buffer capture VT sequence and VT sequence for requesting window/text area's character size.

.github/workflows/codechecker-analysis.yml
Add a new CI job that runs the latest CodeChecker with the latest nightly Clang and analyses the project.
If a **push** happens to `master`, the Clang Static Analyser will work in [Cross-Translation-Unit analysis](http://clang.llvm.org/docs/analyzer/user-docs/CrossTranslationUnit.html) mode. This increases the ability to find more bugs and more versatile reports when functions are called that are defined outside of the current TU, but it increases both the analysis time and the ability for Clang to *crash* immensely.
In every other case, e.g. for **pull requests** and to commit to non-`master` branches, the normal (analysis restricted to current translation unit only) analysis will be done.
In both modes, Clang-Tidy is executed too.
The tally of the findings is printed by `CodeChecker …
=> Clang Static Analyser + Clang-Tidy in the CI

.github/codechecker_config/config.json, .github/codechecker_config/skipfile.txt, .github/workflows/codechecker-analysis.yml
The following improvements were made:
* Put the common configuration of the analysis into a dedicated config file to deduplicate parts of the CI.
* Ignore external code sources, like `Build/3rdparty` and `/usr/include` from the analysis.
* TUs (CPP files) that are in these paths will not be invoked the analysis for, at all.
* AFAIK (but I might be wrong in this), analysis findings that are reported to files in these directories (e.g. headers in `/usr/include`) will be culled from the analysis. This might be detrimental in case a bogus usage of the STL starts from a core Contour TU but the "null dereference" is in the STL or something like that. Will have to see where this leads us...
* Added a new action in the CI that shows the result summary to the CI standard output itself
=> [CodeChecker] Ignore external third party libraries and generated code from analysis

.github/workflows/codechecker-analysis.yml
Because the CI does not run a web server, there is no need to download and use NodeJS and the "web" part of CodeChecker.
In addition, this patch makes the presentation of the analysis results better by adding LLVM version to the artefact name.
=> [CI] CodeChecker: Speed up analysis

.github/workflows/codechecker-analysis.yml
Originally, it was the `analyze` command which signalled through the exit status that _"some reports were found"_. Now, Ericsson/CodeChecker#3232 *moved* this weirdness to the `parse` command.
CI script pulled after that, now we're also ignoring the exit status of the `parse` command. Hopefully this will make it so that the analysis artefacts are collected properly...
=> [CI] CodeChecker: Fix build breaking due to exit status signalling "reports found"

cmake/Version.cmake, scripts/release-ppa.sh, src/contour/CMakeLists.txt, src/contour/ContourApp.cpp
This is how the CLI syntax would look like with this change:
/cc @whisperity
=> [contour] Changes CLI parameters `output` to `to` in all cases except for capture command.

.github/workflows/codechecker-analysis.yml
Turns out that now the `parse` command shows non-zero exit status in case reports are emitted to HTML...
=> [CodeChecker] Fix CI fail by `parse` command broken again

.github/workflows/build.yml, .github/workflows/codechecker-analysis.yml, scripts/ci-prepare-contour.sh
> Follow-up for #226
Sorry, I actually broke one half in the previous patch.
=> [CI] Fix CodeChecker again - `analyze` needs the exit status ignored

Changelog.md, src/terminal/Functions.h, src/terminal/Screen.cpp, src/terminal/Screen.h, src/terminal/Screen_test.cpp, src/terminal/Sequencer.cpp
Closes #16, #18, #19.
`DECRQCRA`- request checksum of rectangular area
=> Adds rectangular area related VT sequences

Changelog.md, src/terminal/pty/UnixPty.cpp, src/terminal/pty/UnixPty.h, src/terminal_view/TerminalView.cpp
=> Fixes `ioctl(..., TIOCGWINSZ, ...)` pixel values that were only set during resize but not initially. Fixes #241.

TODO.md, autogen.sh, src/contour/TerminalDisplay.h, src/contour/helper.cpp, src/contour/helper.h, src/contour/opengl/OpenGLRenderer.cpp, src/contour/opengl/OpenGLRenderer.h, src/contour/opengl/TerminalWidget.cpp, src/contour/opengl/TerminalWidget.h, src/terminal_renderer/GridMetrics.h, src/terminal_renderer/RenderTarget.h, src/terminal_renderer/Renderer.cpp, src/terminal_renderer/Renderer.h
moving some more non-OpenGL logic out of the OpenGL widget (`contour/opengl/TerminalWidget.cpp`)
=> [contour] Some more OpenGL widget cleanups.

autogen.sh
In zsh, realpath $0 returns ".", not an absolute path.
Thus it is necessary to obtain the absolute path since otherwise cmake "${ROOTDIR}" will look for a CMakeLists.txt in the build directory.
=> Fix invalid detection of source path in autogen script

cmake/ThirdParties.cmake
Change `FetchContent_Populate()` to a pair of `FetchContent_Declare()` + `FetchContent_Populate()` to allow offline builds via `FETCHCONTENT_FULLY_DISCONNECTED` variable.
=> Make offline builds possible

Changelog.md, src/contour/Actions.cpp, src/contour/Actions.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/contour.yml
Implements "Clear Scrollback and reset" action.
A action for "Clear scrollback" can be done with adding a special action via `WriteChars` and sending `\e[3J`.
Refs #263.
=> Adds action `ClearHistoryAndReset`

src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/contour.yml, src/contour/helper.cpp, src/contour/helper.h, src/terminal/CMakeLists.txt, src/terminal/InputBinding.h, src/terminal/InputGenerator.cpp, src/terminal/InputGenerator.h, src/terminal/MatchModes.cpp, src/terminal/MatchModes.h, src/terminal/Terminal.cpp, src/terminal/Terminal.h, src/terminal/Terminal_test.cpp
Reworks `input_mapping`, implicitly fixing recently added support to match on terminal states (such as alt screen or not alt screen)
=> Rework input bindings to properly support mode matching.

Changelog.md, src/contour/Config.cpp, src/contour/contour.yml, src/terminal/MatchModes.cpp, src/terminal/MatchModes.h
Makes it possible to copy to clipboard via Ctrl+C iff some text is selected, otherwise it's forwarded to the app.
Closes #292.
=> Implements conditional input mappings based on whether or not the user has selected some text. Closes #292.

autogen.sh, src/contour/opengl/CMakeLists.txt, src/contour/opengl/TerminalWidget.cpp, src/contour/opengl/TerminalWidget.h, src/crispy/debuglog.h, src/terminal/CMakeLists.txt, src/terminal/RenderBuffer.cpp, src/terminal/RenderBuffer.h, src/terminal/Screen.cpp, src/terminal/ScreenEvents.h, src/terminal/Terminal.cpp, src/terminal/Terminal.h, src/terminal_renderer/Renderer.cpp
=> fixes and improvements to synchronized updates

src/contour/ContourApp.cpp, src/contour/opengl/TerminalWidget.cpp, src/crispy/App.cpp, src/crispy/App.h, src/terminal/Grid.h, src/terminal/Screen.cpp, src/terminal/Screen.h
=> improve debug state dumping (also for SEGV)

src/contour/helper.cpp
```c++
#if QT_DEPRECATED_SINCE(5, 15)
// Actually deprecated since 5.0, in docs
QT_DEPRECATED_VERSION_X_5_15("Use angleDelta()")
inline int delta() const  { return qt4D; }
// Actually deprecated since 5.0, in docs
QT_DEPRECATED_VERSION_X_5_15("Use angleDelta()")
inline Qt::Orientation orientation() const { return qt4O; }
```
=> Fixing Qt6 compatibility

src/terminal/CMakeLists.txt, src/terminal/Parser.cpp, src/terminal/Parser.h, src/terminal/ParserEvents.h, src/terminal/Process.h, src/terminal/Screen.cpp, src/terminal/Screen.h, src/terminal/Sequencer.cpp, src/terminal/Sequencer.h, src/terminal/bench-headless.cpp
While this could be merged early already, it only makes more sense if almost all points below are satisfied:
- Making Line a view over the `vector<Cell>` would make text reflow almost a no-op.
- Chunked ASCII text appending should be almost as simple as `memcpy`.
All the above points are nice but would exceed a small PR and fill a dedicated release cycle. Cutting down.
=> Initial work on improving ASCII text throughput performance.

CMakeLists.txt, Changelog.md, cmake/ThirdParties.cmake, src/contour/CMakeLists.txt
My results with `tbp`.
Without mimalloc:
many_lines:   3.0420 seconds,   9.357 MB/s (normalized:   2.457 KB/s)
long_lines:   1.0080 seconds,  29.630 MB/s (normalized:   7.780 KB/s)
sgr_fg_lines:   0.0585 seconds,  54.701 MB/s (normalized:  14.362 KB/s)
sgr_fg_bg_lines:   0.0724 seconds,  44.199 MB/s (normalized:  11.605 KB/s)
all tests:   5.0809 seconds,  22.035 MB/s (normalized:   5.786 KB/s)
With mimalloc:
many_lines:   3.0456 seconds,   9.259 MB/s (normalized:   2.431 KB/s)
long_lines:   1.0202 seconds,  26.622 MB/s (normalized:   6.990 KB/s)
sgr_fg_lines:   0.0526 seconds,  60.837 MB/s (normalized:  15.973 KB/s)
sgr_fg_bg_lines:   0.0523 seconds,  61.185 MB/s (normalized:  16.065 KB/s)
all tests:   5.0707 seconds,  22.429 MB/s (normalized:   5.889 KB/s)
=> Using mimalloc (experimental, optionally)

.clang-tidy, .github/codechecker/config.json, .github/workflows/codechecker-analysis.yml
(Also enable using the latest nightly PPA LLVM for the analysis instead of the release version,)
=> [CI][CodeChecker] Add the "swapped/swappable" parameters checkers into the enabled list explicitly

src/contour/helper.cpp, src/contour/helper.h, src/contour/opengl/TerminalWidget.cpp, src/contour/opengl/TerminalWidget.h
This fixes a crash when `_fonts.size.pt` is somehow zero.
=> Always sanitize font description

src/contour/ContourGuiApp.cpp
Because:
>ContourGuiApp.cpp:173:40: warning: ‘Qt::AA_DisableHighDpiScaling’ is deprecated: High-DPI scaling is always enabled. This attribute no longer has any effect. [-Wdeprecated-declarations]
173 |     QCoreApplication::setAttribute(Qt::AA_DisableHighDpiScaling);
It's cosmetic change, but I don't like warnings. :)
=> Don't use AA_DisableHighDpiScaling with Qt 6

.github/codechecker/skipfile.txt
At some point the past two-ish months the layout of the build changed and the previous skip-list did not properly ignore not-to-be-analysed third-parties anymore, resulting in 340-ish analysis actions, compared to the 150-ish that should have been.
=> [CI][CodeChecker] Update skip-list

src/crispy/LRUCache.h, src/terminal_renderer/TextRenderer.cpp, src/terminal_renderer/TextRenderer.h
=> TextRenderer cleanup / refactor / LRU-cache uses

autogen.sh, src/contour/opengl/CMakeLists.txt, src/contour/opengl/TerminalWidget.cpp
Minor OpenGL version related cleanups, and remove hard dependency on OenGL at compile time.
Related to #166.
This is an attempt to make it possible to use the OpenGL software rasterizer. However, setting `Qt::AA_UseSoftwareOpenGL` (even before Q(Gui)Application was created) did not automatically enable the use of the OpenGL software rasterizer on Linux (Gentoo).
I still had to force it via environment variable  `LIBGL_ALWAYS_SOFTWARE=1`
=> OpenGL version related cleanups and hard-dependency drop.

Changelog.md, src/terminal/Screen.cpp
The other problem of #406 is how we want to treat the question of whether or not to append a linefeed at the end of a received and rendered Sixel image... Maybe that should be addressed separately.
=> Fixes SEGV with overflowing (Sixel) images. 

Changelog.md, src/contour/helper.cpp
Addresses at least the Sixel image sizes issue related to terminal window resizes in #408
=> Fixes internal pixel width/height tracking

Changelog.md, src/contour/Config.cpp, src/terminal/Capabilities.cpp
also helps OS/X's terminfo issue (primitively at least)
=> Automatically detect if `contour` or `contour-latest` terminfo entries are present use that as default.

Changelog.md, src/terminal_renderer/BoxDrawingRenderer.cpp
Fixes at least the SEGV as triggered by `notcurses-info`  (#424, box drawing for diagonals could sometimes be writing one byte passt the buffer.
=> Fixes off-by-one bug in builtin box drawing.

Changelog.md, src/terminal_renderer/BoxDrawingRenderer.cpp, src/terminal_renderer/BoxDrawingRenderer.h, src/terminal_renderer/TextRenderer.cpp
refs #424, #441
closes #437, #419
Update: I am not going to implement all possible box drawings and terminal-alike codepoints in one single PR.
Ticket #441 is used to keep track of the progress.
=> Adds more pixel-perfect graphical codepoints.

src/contour/Config.cpp
The previous implementation of `softLoadFont` added nodes to `_usedKeys` incorrectly, so the got warnings when starting `contour` with default config.
=> Fix `Superfluous config key found` warnings

README.md, src/contour/Config.cpp, src/contour/Config.h, src/contour/ContourGuiApp.cpp, src/contour/contour.yml
Add the CLI option `class` and the configuration option `wm_class` to set the user-defined `WM_CLASS` property of the terminal window.
This could be tested using `xprop` utility, to test if we really modified `WM_CLASS`:
```
WM_CLASS(STRING) = "contour", "contour_ex"
```
I additionally tried to use this feature with my `i3wm` as it described in #376, using the following configuration:
```
for_window [class="contour_ex"] floating enable
```
It works as expected in both cases: when set using the CLI option or using a configuration file.
=> Add option to set a custom `WM_CLASS`

Changelog.md, src/contour/Config.cpp, src/contour/TerminalSession.cpp, src/contour/contour.yml, src/terminal/Screen.h
no bug reports, nothing found myself. no need to flag it as experimental then.
=> [contour] Enables TCAP query feature by default, removes experimental flag, not configurable anymore.

Changelog.md, src/contour/ContourGuiApp.cpp
This is:
- session resuming (fixes #461)
- QPA platform setting
- X11 display setting
Mind, this does not provide fully fledged session management. It simply makes sure resmed contour instances via session ID will work (i.e. not crash).
=> [contour] Extents CLI parameters to support those that Qt supports by default.

src/contour/contour.desktop
Many apps uses this way.
E.g. I **always** install my compiled binaries to `/usr/local/bin`.
=> Don't use absolute path to contour in contour.desktop

Changelog.md, scripts/install-deps.sh, src/terminal_renderer/BoxDrawingRenderer.cpp
So that Fira Code does not look shit on a ZSH prompt using p10k.
Reference: https://github.com/ryanoasis/powerline-extra-symbols#glyphs
=> Adds pixel-perfect box-drawing for U+E0B4, U+E0B6, U+E0BC, U+E0BE

src/text_shaper/open_shaper.cpp
FT_Get_Char_Index as per documentation at https://freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_get_char_index returns 0 in case of an error. It does not return a Freetype2 error code. Thus checking for FT_Err_Ok which is defined to 0 does not really make any sense.
Fixes #536
=> (#536) Fix SIGFPE on FreeBSD

.github/fedora/Dockerfile, .github/fedora/contour.spec, .github/workflows/build.yml, .github/workflows/release.yml
Hey, hope you're doing well! :)
This PR aims to resolve #420 by adding RPM packaging for Fedora (didn't tried in openSUSE which also uses RPM packages but it should work _in theory_). I'm actually using a RPM package produced from my tests and it's working really good btw.
Regarding to structure I tried to keep the same hierarchy as ArchLinux builds, made a directory in `.github/` called `fedora` that contains the following files:
- `Dockerfile` - our Fedora docker container image used to build contour RPM package.
- `contour.spec` - our spec file used to compile contour as a RPM package (contains all the packaging logic).
Also I'm only packaging for `x86_64` arch at the moment, if it's requested then I could also add packaging for `arm64`/`aarch64`.
Please let me know if you want me to …
=> feat(ci): add RPM packaging

debian/contour-terminfo.install, debian/contour.install
=> debian: Adds missing terminfo file to .deb file.

.github/workflows/build.yml, .github/workflows/release.yml
Currently, the Ubuntu 18.04 `.deb` is broken because the control file
doesn't match what is installable (and for the CI itself, installed)
from the system packages.
This new test job ensures that the build only passes if the package
created by the CI can actually be installed on the system.
=> [CI][Ubuntu] Test `dpkg --install` the `.deb` output

Changelog.md, src/contour/Config.cpp, src/contour/Config.h, src/contour/ContourGuiApp.cpp, src/contour/contour.yml
Not sure how this is possible with Qt, but it would be useful (for customers) to determine if the underlying hardware OpenGL implementation is prior 3.0 and then just default-select software rendering.
Note, the current "software" renderer is making use of the system provided OpenGL software renderer.
Why is `Apple Software Renderer` causing a SEGV? ;-(
=> [contour] Adds config key `renderer` to choose a renderer: default, software, OpenGL.

.github/mock-font-locator.yml, .github/workflows/external_tests.yml, Changelog.md, scripts/ci/Xvfb-contour-run.sh, scripts/install-deps.sh, src/contour/Config.cpp, src/contour/Config.h, src/contour/ContourGuiApp.cpp, src/contour/ContourGuiApp.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/terminal/CMakeLists.txt, src/terminal/InputGenerator.cpp, src/terminal/InputGenerator.h, src/terminal/Screen.cpp, src/terminal/Sequencer.cpp, src/terminal/Terminal.cpp, src/terminal/Terminal.h, src/terminal/logging.h, src/terminal/pty/UnixPty.cpp, src/terminal_renderer/TextRenderer.cpp, src/terminal_renderer/TextRenderer.h, src/text_shaper/CMakeLists.txt, src/text_shaper/mock_font_locator.cpp, src/text_shaper/mock_font_locator.h
I'm giving up on ASAN for now. I was indeed able to avoid fontconfig memory leak but can't get rid of the Qt ones. Trying later. This PR still contains some good refactors and cleanups.
=> CI: trying to get external tests ASAN to pass

src/contour/Config.cpp, src/contour/opengl/OpenGLRenderer.cpp, src/contour/opengl/TerminalWidget.cpp, src/crispy/CMakeLists.txt, src/crispy/StrongHash.h, src/crispy/StrongLRUCache.h, src/crispy/StrongLRUCache_test.cpp, src/crispy/StrongLRUHashtable.h, src/crispy/StrongLRUHashtable_test.cpp, src/crispy/assert.h, src/terminal/Cell.h, src/terminal/Image.cpp, src/terminal/Image.h, src/terminal/RenderBuffer.h, src/terminal/Screen.cpp, src/terminal/Screen.h, src/terminal/Screen_test.cpp, src/terminal/Terminal.cpp, src/terminal_renderer/ImageRenderer.cpp, src/terminal_renderer/ImageRenderer.h, src/terminal_renderer/Renderer.cpp, src/terminal_renderer/TextRenderer.cpp, src/terminal_renderer/TextRenderer.h
- the cleanups should happen as part of the LRU cache.
- can we maintain a free-list for the texture atlas? sounds like a hard problem wrt efficient use of re-using the space
- ...
This is a PREP-WORKS-PR, the actual renderer changes (addressing the above) I'll do in a follow-up PR.
=> fixing render cache bloat - prep-work

Changelog.md, src/terminal/Grid.cpp, src/terminal/Screen.h
@whisperity that's the one for you and `aptitude`'s scroll-up issue :-)
It was using DECSC -> DECSTBM -> DECRC -> LF DECSTBM .... and the DECRC was not restoring to the correct position (in fact, it has been drunk).
=> Fixes DECRC

src/terminal/Sequencer.cpp
Should be closing #576 as soon as I understand the abab/cdcd/efef pattern phenomenon.
=> [terminal] Sequencer: Fixes OSC 4 reply (include color index).

scripts/install-deps.sh
I don't know if it's a typo, but all packages are in the official
repo, so we should using pacman
=> Use pacman instead of packman

Changelog.md, src/terminal/Screen_test.cpp, src/terminal/Sequencer.cpp
Adds support for setting color via `OSC 4 ; INDEX ; #RRGGBB ST`. This format is also supported by `XParseColor` and at least one application is making use of it ([kfc](https://github.com/mcpcpc/kfc)).
Thanks @subnut for the hint.
Reference: https://github.com/contour-terminal/contour/issues/221#issuecomment-1025982122
=> [terminal] Fixes VT sequence `OSC 4` to also support setting color via `#RRGGBB` and `#RGB`.

src/contour/Config.cpp, src/contour/TerminalSession.cpp, src/contour/opengl/OpenGLRenderer.cpp, src/contour/opengl/OpenGLRenderer.h, src/contour/opengl/TerminalWidget.cpp, src/terminal/ColorPalette.cpp, src/terminal/ColorPalette.h, src/terminal_renderer/RenderTarget.h, src/terminal_renderer/Renderer.cpp
Have background image loaded in host memory only once and only until it's uploaded to the GPU.
=> Further reduce host-memory usage.

src/terminal/Screen_test.cpp, src/terminal/Terminal.cpp, src/terminal/primitives.h
For some reason, `apt` tool sends out an invalid `DECSTBM` sequence, such as `CSI 0 ; 26 r` with 26 being the bottom line and 0 the top line. But 0 should have been at least 1, as screen coordinates are 1-based.
Fixes #631
=> Fixes assertion on bad use of DECSTBM

.github/workflows/build.yml, .github/workflows/external_tests.yml, src/contour/CMakeLists.txt
> Closes #632 
CPackDeb is ridiculously broken, but I've found a workaround so now we can properly generate debuginfo.
It needs to have a component, even if the program package is a single thing binary only.
=> [CI] Upload Ubuntu `ddeb`s as artefacts

Changelog.md, src/contour/Config.cpp, src/contour/contour.yml, src/crispy/App.cpp, src/crispy/BufferObject.cpp, src/crispy/utils.h, src/terminal/Process.h, src/terminal/Process_unix.cpp, src/terminal/RenderBufferBuilder.cpp, src/terminal/Terminal.cpp, src/terminal/pty/ConPty.cpp, src/terminal/pty/ConPty.h, src/terminal/pty/MockPty.cpp, src/terminal/pty/MockPty.h, src/terminal/pty/Pty.h, src/terminal/pty/UnixPty.cpp, src/terminal/pty/UnixPty.h
Fixes #647.
Also contains general improvements / cleanups.
I think we could further improve the behavior...
Currently: any argument at the end of the CLI that can't be parsed is treated as shell program to spawn. This mimics KDE's konsole and the way KDE desktop is spawning apps in a terminal.
If that command however cannot be executed, an error message is being printed into the terminal.
=> Overall improvements and fix to #647

Changelog.md, docs/input-modes.md, src/contour/Actions.cpp, src/contour/Actions.h, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/contour.yml, src/crispy/utils.h, src/terminal/CMakeLists.txt, src/terminal/Cell.h, src/terminal/ColorPalette.h, src/terminal/InputHandler.h, src/terminal/Line.h, src/terminal/MatchModes.h, src/terminal/RenderBufferBuilder.cpp, src/terminal/RenderBufferBuilder.h, src/terminal/Screen.h, src/terminal/Terminal.cpp, src/terminal/Terminal.h, src/terminal/TerminalState.cpp, src/terminal/TerminalState.h, src/terminal/ViCommands.cpp, src/terminal/ViCommands.h, src/terminal/ViInputHandler.cpp, src/terminal/ViInputHandler.h, src/terminal/Viewport.cpp, src/terminal/Viewport.h, src/terminal/primitives.h
Implements #282.
I think i'll (have to) address the remaining events mentioned in #641.
=> vi-like input modes

Changelog.md, src/contour/Config.cpp, src/contour/Config.h, src/contour/contour.yml, src/terminal/Cell.h, src/terminal/ColorPalette.cpp, src/terminal/ColorPalette.h, src/terminal/Line.h
Fixes #664
Also adds profile config option: `draw_bold_text_with_bright_colors` (default false).
Prior to this PR, bold text was always rendered with bright colors additionally to using the bold font face. Now this is configurable (defaulting to false, however).
=> customizable dim (faint) colors.

src/terminal/VTWriter.cpp, src/terminal/VTWriter.h
Addresses an issue mentioned in #651.
=> [terminal] VTWriter: reliably write out RGB colors and indexed colors.

Changelog.md, src/terminal/Screen.cpp, src/terminal/Screen.h
Addresses inconsistency with xterm's implementation of XTSMGRAPHICS `\e[?2;1;0S` as mentioned in #656.
=> [terminal] Fixes `XTSMGRAPHICS` when querying sixel image limits, to be capped at terminal viewport dimensions (#656).

Changelog.md, src/terminal/Charset.h, src/terminal/Screen.cpp
=> [terminal] Fixes SGR and text breakage when altering charsets via `ESC ( 0` VT sequence (#661).

Changelog.md, src/terminal/Terminal.cpp
Fixes lagging output with synchronized updates using [rainbowbench](https://github.com/lhecker/rainbowbench) on Mac.
=> Fixes Synchronized Updates (`SM/RM ? 2026`) sometimes lagging behind in rendering.

README.md, src/crispy/CMakeLists.txt, src/crispy/StrongHash.h, src/crispy/StrongLRUCache.h, src/crispy/StrongLRUHashtable.h, src/crispy/sse2neon.h
I've made a bit of progress on issue #611 
I've used sse2neon.h from https://github.com/DLTcollab/sse2neon (it's MIT licensed; I hope that's compatible) to get contour to compile on aarch64.
I also made the necessary changes to src/crispy/CMakeLists.txt as well, but I only replaced -maes with the relevant ARM options, so it will break the build on x86_64. Perhaps someone who knows cmake better than I do knows how to switch options based on target architecture?
=> Made necessary changes to compile on aarch64

.github/workflows/build.yml, Changelog.md, src/contour/Actions.cpp, src/contour/Actions.h, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/contour.yml, src/contour/helper.cpp, src/crispy/BufferObject.h, src/terminal/Functions.h, src/terminal/RenderBufferBuilder.cpp, src/terminal/RenderBufferBuilder.h, src/terminal/Screen.cpp, src/terminal/Screen.h, src/terminal/Sequencer.cpp, src/terminal/Sequencer.h, src/terminal/Terminal.cpp, src/terminal/Terminal.h, src/terminal/TerminalState.cpp, src/terminal/TerminalState.h, src/terminal/primitives.h, src/terminal/pty/LinuxPty.cpp, src/terminal/pty/UnixPty.cpp, src/terminal_renderer/Renderer.cpp
References #687.
host writable status line and switching is already working. Indicator and configurability of Indicator is not yet.
Indicator status line: when we want to write arbitrary VT sequences, it MUST have its own VT parser state.
I think having the Indicator status line configurable should be its own PR as a separate feature step, not not make this PR too complex
=> Implements DECSASD, DECSSDT (VT status line)

Changelog.md, src/contour/Actions.cpp, src/contour/Actions.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/contour.yml, src/terminal/Terminal.cpp, src/terminal/Terminal.h
Closes #697.
Utilizing (already existing) DECKAM for this feature.
=> [contour] Adds new input action `ToggleInputProtection` to protect terminal application against accidental input (#697).

Changelog.md, src/contour/ContourApp.cpp, src/contour/ContourApp.h, src/crispy/escape.h, src/terminal/Functions.h, src/terminal/InputGenerator_test.cpp, src/terminal/Screen.cpp, src/terminal/VTType.h
Implements #730
<details>
<summary>It currently looks like something like this:</summary>
```txt
C0 sequences
============
EOT                  EOT             End of Transmission (VT100)
BEL                  BEL             Bell (VT100)
BS                   BS              Backspace (VT100)
TAB                  TAB             Tab (VT100)
LF                   LF              Line Feed (VT100)
VT                   VT              Vertical Tab (VT100)
FF                   FF              Form Feed (VT100)
CR                   CR              Carriage Return (VT100)
SO                   SO              Shift Out; Switch to an alternative character set.  (VT100)
SI                   SI              Shift In; Return to regular character set after Shift Out. (VT100)
ESC sequences
============= …
```
=> Adds CLI syntax `contour info vt` to print list of supporte VT sequences

.github/fedora/contour.spec, Changelog.md, scripts/ci/notcurses-install-deps.sh, scripts/install-deps.sh, src/contour/Audio.cpp, src/contour/Audio.h, src/contour/CMakeLists.txt, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/crispy/span.h, src/terminal/Functions.h, src/terminal/Screen.cpp, src/terminal/Sequence.h, src/terminal/Terminal.h
=> adds vt sequence `DECPS`

src/terminal/Line.cpp, src/terminal/Line.h, src/terminal/Line_test.cpp, src/terminal/RenderBuffer.h, src/terminal/RenderBufferBuilder.cpp, src/terminal/RenderBufferBuilder.h, src/terminal/Screen.cpp, src/terminal/Screen.h, src/terminal/Screen_test.cpp, src/terminal/VTWriter.cpp, src/terminal_renderer/BackgroundRenderer.cpp, src/terminal_renderer/DecorationRenderer.cpp, src/terminal_renderer/TextRenderer.cpp
Based on the work at #742.
Should be closing #738.
@Utkarsh-khambra - please look at the diff per commit individually.
The first commit does some refactorings, reducing some code duplications by introducing `RenderAttributes`. This looks like a little bit of overkill at first, but makes sense in the third commit.
The second commit simply renames the trival-line buffer struct to `TrivialLineBuffer` to finally fix my brain damage and hopefully have a nice and yet still self-explaining type name. :)
The third commit **actually fixes** the line inflation bug by differenciating between SGR at the time of line creation/erase/reset versus current SGR at the time of actually writing the text.
@Utkarsh-khambra I by no means intended to steal that from you, but I hoped to give you a less intrusive …
=> Trivial line related refactors and an alternative less intrusive fix proposal.

src/terminal/Line.cpp, src/terminal/Line.h, src/terminal/Terminal.cpp
=> Removes `fillRemainingCells`, which clears line on `CSI 0m`

src/contour/TerminalSession.cpp, src/contour/display/TerminalWidget.cpp, src/contour/helper.cpp, src/terminal/Cell.h, src/terminal/Color.h, src/terminal/RenderBufferBuilder.cpp, src/terminal/RenderBufferBuilder.h
When colorscheme's cursor color is set to inverted CellBackground/CellForeground, it seems that a bug has slipped in and the cursor becomes unreadable when cursor shape is block.
This PR primarily factors grid cell colorization with respect to: isCursor / cell hidden / reverse video / actual SGR / configured selection colors / configured highlight colors.
I think the bug was introduced after last release, so no changelog entry really needed.
=> Fixing text cursor coloring along with some code cleanups.

Changelog.md, src/contour/display/OpenGLRenderer.cpp, src/terminal_renderer/BackgroundRenderer.cpp, src/terminal_renderer/BoxDrawingRenderer.cpp, src/terminal_renderer/DecorationRenderer.cpp, src/terminal_renderer/GridMetrics.h, src/terminal_renderer/TextRenderer.cpp, src/text_shaper/directwrite_shaper.cpp, src/text_shaper/open_shaper.cpp
This is a prep-work refactor for the future move to Qt QML / QtQuick. There, the coordinate system (as in every GUI app) top left is (0, 0) and not bottom left (0, 0).
OpenGL however is the other way around. Qt internally seems to go the GUI way (just like web browsers do, too, so yeah, maintaining two coordinate systems is PITA).
This prep-work ought to make it easier in future QtQuick refactor to adhere to `QQuickitem`'s positioning and transformation API.
=> Inverting rendering coordinate system's Y-axis.

Changelog.md, cmake/FilesystemResolver.cmake, src/contour/CMakeLists.txt, src/contour/contour.desktop, src/contour/metainfo.xml
Contains an improved .desktop file, better file naming for that as well as for the application icon and provides an AppStream XML file.
This is the result coming out of https://github.com/flathub/flathub/pull/3349. Wth that merged and a potential next release on flatpak, the respective patch file from the flatpak repo must be removed to not break future releases.
Refs #766
=> Applying some tweaks with regards to Flatpak and AppStream (XML) recommendations.

Changelog.md, src/contour/BlurBehind.cpp
Implement what is said in https://github.com/aunetx/blur-my-shell#application-blurring
Refs #52.
I did NOT test this yet. it should work on GNOME shell as far as I understood it. (famous last words).
EDIT: seems like blur-my-shell GNOME shell extension is needed for this to work. I couldn't get it to work yet though.
Waiting on input from https://github.com/aunetx/blur-my-shell/issues/300
=> Adds support for blur-behind window on GNOME shell.

Changelog.md, src/contour/TerminalSession.cpp, src/terminal/Process.h, src/terminal/Process_unix.cpp, src/terminal/pty/ConPty.cpp, src/terminal/pty/ConPty.h, src/terminal/pty/LinuxPty.cpp, src/terminal/pty/LinuxPty.h, src/terminal/pty/MockPty.cpp, src/terminal/pty/MockPty.h, src/terminal/pty/MockViewPty.cpp, src/terminal/pty/MockViewPty.h, src/terminal/pty/Pty.h, src/terminal/pty/UnixPty.cpp, src/terminal/pty/UnixPty.h
While I do need this change for my QML port of the frontend (as a work-around on a Qt5 bug!), this might still be helpful for the behavior mentioned in #773, where `xdotool` is run during shell initialization but the window may not be visible just yet.
This PR will defer the PTY & shell process creation until it cannot be deferred anymore.
=> defer PTY (and Process) creation

Changelog.md, src/contour/TerminalSession.cpp, src/terminal/Process_win32.cpp, src/terminal/Terminal.cpp, src/terminal/Terminal.h, src/terminal/TerminalState.h, src/terminal/ViCommands.cpp, src/text_shaper/directwrite_shaper.cpp, src/text_shaper/directwrite_shaper.h, src/text_shaper/font_locator_provider.h
@whisperity I know you once asked for it. 
While I think this is useful already - I did it as API prep-work for incremental search (which also needs the statusline :) )
=> [terminal] Always show indicator status line when ANSI mode KAM is enabled (which can be toggled via action `ToggleInputProtection`).

Changelog.md, src/terminal/ViCommands.cpp
it was implemented by accident in KAM-visual-statusline already, but accidentally inverted. This PR is basically fixing it plus adding a changelog, such that the indicator statusline is being shown when entering normal/visual mode and hidden when entering insert (default) mode.
=> [terminal] Always show indicator status line when in non-insert mode.

scripts/ci/notcurses-install-deps.sh, scripts/install-deps.sh, src/contour/BlurBehind.cpp, src/contour/CMakeLists.txt
Refs #52.
The PR #771 dropped kwin dependency but didn't do it right. `QWindow::setProperty(...)` is indeed NOT setting X11 like properties but that function is related to Qt properties.
This most likely might be fixing the issue at https://github.com/aunetx/blur-my-shell/issues/300. Sorry for the noise. :)
=> Fixing blur-behind for XCB platforms.

Changelog.md, src/terminal/Process.h, src/terminal/Process_unix.cpp, src/terminal/Process_win32.cpp, src/terminal/pty/LinuxPty.cpp
Apparrently one shall not enable controlling terminal for the child process, which happens to be flatpak-spawn when running within flatpak sandboxed environment. This is just a workaround for something that is hopefully(!) fixed soon-ish.
Apart from that, flatpak-spawn is now also properly forwarding file descriptor `3` (stdout-fastpipe).
- https://github.com/flatpak/flatpak/issues/3697
- https://github.com/flatpak/flatpak/issues/3285
=> Work around flatpak PTY related bugs

Changelog.md, src/contour/Config.cpp, src/contour/ContourGuiApp.cpp, src/contour/ContourGuiApp.h, src/terminal/Process_unix.cpp, src/terminal_renderer/TextRenderer.cpp
=> Flatpak: Exposes TERMINFO environment variable pointing to a valid path containing the contour terminfo file.

Changelog.md, src/contour/Config.cpp, src/contour/contour.yml, src/terminal/Process.h, src/terminal/Process_unix.cpp, src/terminal/Process_win32.cpp
Setting this option really only makes sense when running via Flatpak (or other sandboxed environments in the future).
By default, the sandbox is (and used to be) always escaped. But rarely it makes sense not to.
=> [Flatpak] Adds configuration key `profiles.*.escape_sandbox`

.github/workflows/build.yml, .github/workflows/external_tests.yml, .github/workflows/release.yml, metainfo.xml, scripts/ci/notcurses-install-deps.sh, scripts/install-deps.sh, src/contour/CMakeLists.txt
- https://docs.appimage.org/packaging-guide/from-source/native-binaries.html#packaging-from-source
=> Adding AppImage packaging

metainfo.xml, src/contour/TerminalSession.cpp, src/terminal/Screen.cpp, src/terminal/Screen_test.cpp, src/terminal/TerminalState.cpp, src/terminal/primitives.h
Mentioned in #809.
Implementation of DECSDM was flipped. To make it clear for the future, I've also renamed the enum value itself, so that I'm not getting confused again.
=> Fixes interpretation of DECSDM to disable Sixel auto-scrolling, if enabled.

metainfo.xml, src/terminal_renderer/TextRenderer.cpp, src/terminal_renderer/TextRenderer.h
=> Improve startup-time by not pre-rasterizing all printable US-ASCII codepoints at once

metainfo.xml, src/terminal_renderer/TextRenderer.cpp, src/text_shaper/open_shaper.cpp
Fixes #821. Seems to only affect LCD subpixel rendering and only for (direct mapped) US-ASCII glyphs.
=> Fixes issue for some oversized glyphs.

metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/contour.yml, src/terminal/Screen.cpp, src/terminal/Screen_test.cpp, src/terminal/SixelParser.cpp, src/terminal/SixelParser_test.cpp
fixes #822
To test this use [this script](https://github.com/hackerb9/vt340test/blob/main/jerch/gcrglf.sh). Since the script requires cell height to be 20px, you can change font size to be 11 in default config with monospace font family.
=> Now moves cursor vertically for sixel newlines even if there is no sixel

metainfo.xml, src/terminal_renderer/ImageRenderer.cpp, src/terminal_renderer/ImageRenderer.h, src/terminal_renderer/RenderTarget.cpp, src/terminal_renderer/RenderTarget.h, src/terminal_renderer/Renderer.cpp, src/terminal_renderer/TextRenderer.cpp, src/terminal_renderer/TextRenderer.h
Fixes #831 and now it looks like:
=> Sixel rendering for images that show below but should be rendered above text

metainfo.xml, src/terminal/RenderBufferBuilder.cpp
Thank you for taking the time to create a pull request in this repository!
Please fill out this form before submitting your PR.
Please provide a general summary of your changes in the Title above.
```markdown
Bugfix in vi cursor color.
```
```markdown
This pr fixes a bug in vi mode cursor. 
```
If you print some text like `cat someFile` and then switch to VI mode and use vi keybinds to move around, sometimes
cursor is just completely invisible.
=> Fixes vi cursor color

src/terminal/Parser-impl.h, src/terminal/Parser.h, src/terminal/ParserEvents.h, src/terminal/Parser_test.cpp, src/terminal/Screen.cpp, src/terminal/Screen.h, src/terminal/Sequencer.cpp, src/terminal/Sequencer.h, src/terminal/TerminalState.h, src/terminal/bench-headless.cpp
Prepares some generally applicable code refactors ahead of #692.
These refactors are being merged separately because they do not change semantics but simply shift responsibility from other places into the parser.
Specifically:
- Parser now has knowledge of the last (previous) graphic character.
- Parser now handles UTF-8 to UTF-32 conversion itself (rather than Sequencer/Screen.)
=> Some prep-work for VT text processing optimizations.

scripts/install-deps.sh
```markdown
Added fetch of embeded libraries to make it easier to take car of dependencies if OS is not supported
Helps in situations like this #849 
```
- - Checked on blank VM that script is fetching dependencies if OS is not supported and cmake in the future use them
- - has no effect
=> Fetch some embeded libs if OS is not supported

cmake/PedanticCompiler.cmake, metainfo.xml, scripts/install-deps.ps1, scripts/install-deps.sh, src/terminal/Line.cpp, src/terminal/Line_test.cpp, src/terminal/Parser.cpp, src/terminal/Parser.h, src/terminal/ParserEvents.h, src/terminal/Screen.cpp, src/terminal/Screen.h, src/terminal/Screen_test.cpp, src/terminal/Sequencer.cpp, src/terminal/Sequencer.h
=> improve VT text processing efficiency 

README.md
The `mkdir build` command is redundant, as the `cmake -S . -B build` command itself does create the `build` folder if it doesn't exist.
Small efficiency gain by recommending one command less in the build instructions
=> Remove not needed mkdir from build instructions

metainfo.xml, src/terminal/RenderBufferBuilder.cpp, src/terminal/RenderBufferBuilder.h, src/terminal/Selector.cpp, src/terminal/Selector.h, src/terminal/Terminal.h
The code was basically there already. But what was missing is the check to see if the fast path could be used for rendering the trivial line the faster way. So if a line is trivial but does contain some kind of visual modifications to it (currently only possible when parts of such line is selected, because that alters the way a cell is rendered in color), then the fast path cannot be used, otherwise it can.
=> Avoid slow path on rendering trivial line if possible.

metainfo.xml, src/terminal/Terminal.h, src/terminal/TerminalState.h
I found this bug because [slides](https://github.com/maaslalani/slides) did not restore mode switches in reverse order during exit.
=> Fixes restoring the cursor visibility after leaving alternate screen when application wasn't restoring mode switches in reverse order.

src/contour/CMakeLists.txt
```markdown
Correct versioning numbers for macOS download
```
```markdown
Versioning numbers for macOS download  were always 0.1.0_pre
```
=> Correct versioning numbers for macOS download

metainfo.xml, src/terminal/Line.h, src/terminal/ViCommands.cpp
normal mode vertical cursor movements beyond the last character of a new line was snapping to the left. that's more hindering than anything near helpful. 
also, use actual cell width property to decide how many cells to move to the right when having to move to the right.
=> Fixes cursor movement over wide characters in normal mode.

src/contour/Config.cpp
```markdown
Added exception handling on wrong read of provided config file
by creation of valid configuration file and loading it
```
Fixes  #886 
- - checked that on bad configure file contour will create new configure file and load it
=> Handle case when config file is corrupted

src/terminal/Grid.h, src/terminal/RenderBufferBuilder.h, src/terminal/Screen.h, src/terminal/Terminal.cpp, src/terminal/primitives.h
we just recently implemented that.
but it only worked on non-trivial lines.
And trivial lines had to be promoted to inflated lines first (e.g. by clicking into them).
This PR actually auto-promotes all line buffers within the viewport to inflated when a search term is to be highlighted.
Doing it the other way (retain being trivial line buffer and operate on that) sounds more expensive, given the cost-beneficial factor.
=> Improves highlight search matching to also work on trivial line buffers (by promoting them on-demand to inflated line buffers).

CMakeLists.txt, examples/CMakeLists.txt, examples/watch-mouse-events.cpp, metainfo.xml, src/contour/TerminalSession.cpp, src/terminal/InputGenerator.cpp, src/terminal/InputGenerator.h, src/terminal/Screen.cpp, src/terminal/Selector.cpp, src/terminal/Selector.h, src/terminal/Selector_test.cpp, src/terminal/Terminal.cpp, src/terminal/Terminal.h, src/terminal/TerminalState.cpp, src/terminal/ViCommands.cpp, src/terminal/primitives.h
The drafted spec WAS is here: https://gist.github.com/christianparpart/bf82bc3a8ad7f3abeee3ada41c3178a9
but NOW located here: https://github.com/contour-terminal/vt-extensions
This adds support for allowing the terminal application to request mouse events, passively, i.e. the user can still select text as he'd be able to do when no app has requested mouse event tracking.
This feature does make sense in situations where the shell (ZSH, fish, bash, ...) might want to implement:
- reposition the cursor to where the mouse has been clicked in the command prompt
- tooltips of the command the mouse cursor is currently hovering
The problem without implementing such a VT extension is, that shells would never try to implement such features, as the user experience (no mouse-based select support) …
=> VT extension: passive mouse reporting & text selection reporting

metainfo.xml, src/contour/contour.yml, src/vtbackend/ColorPalette.h
it was renamed some time ago already, but apparently the default config file wasn't updated respectively. Sorry about that.
=> Fixes default config entry `draw_bold_text_with_bright_colors` (renamed from `bold_is_bright`).

src/vtbackend/Grid.cpp
fixes  #877
On resize, when we need to unwrap line we add it into  `logicalLineBuffer`, and on next iteration we need to flush it, what was happening before is that in case of `trivialLine` we were skipping flush until we encounter non trivial line, this should not happen 
- checked locally that issue is fixed
=> Fix of resize when next line is trivial

metainfo.xml, src/contour/Actions.h, src/contour/Config.cpp, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/contour.yml, src/crispy/CMakeLists.txt, src/vtbackend/CMakeLists.txt, src/vtbackend/Terminal.h, src/vtbackend/ViCommands.cpp
this allows pasting text with whitespace normalized and newlines replaced with whitespaces,
in order to allow uses like the following:
[contour-normal-mode-copy-and-use-stripped.webm](https://user-images.githubusercontent.com/56763/207688264-5e84e18d-8a1a-4890-a3b3-030c9cc5e52c.webm)
=> Adds optional parameter `strip` to PasteClipboard configuration action

metainfo.xml, src/vtbackend/ViCommands.cpp
Closes #917 
```markdown
The cursor was going past the right end, changed so that cursor cannot get past the right end
```
```markdown
```
see #917 
Doesn't affect any.
=> Don't go past the end of terminal screen in vim mode.

metainfo.xml, src/contour/display/ShaderConfig.cpp
This at least helps me running Contour via Flatpak on ARM64, as (for some reason), it only works through OpenGL/ES.
Not sure this would also help #927 / Wayland.
=> Fixes running within OpenGL/ES context.

metainfo.xml, src/contour/Config.cpp
=> Fixes failing startup due to `background_image.path` pointing to a non-existing file

metainfo.xml, src/contour/Config.cpp, src/contour/contour.yml, src/vtbackend/ColorPalette.h, src/vtbackend/Terminal.cpp
turned out to be incredibly useful when having multiple TEs to not look too invasive.
[contour-indicator-statusline-focus-colors.webm](https://user-images.githubusercontent.com/56763/209105430-59c73b19-29a9-4a35-8c9d-e8f850a1d458.webm)
=> Allow colorizing the indicator status line differently when TE is not in focus.

metainfo.xml, src/contour/display/OpenGLRenderer.cpp
```markdown
Add mirroring of the background image to correctly show it
```
```markdown
Right now background image is inverted in contour. 
In _glTextImage2D_ documentation is written :   
_______________________________________________________________________
The first element corresponds to the lower left corner of the texture image. 
Subsequent elements progress left-to-right through the remaining texels in the lowest row of the texture image,
and then in successively higher rows of the texture image. 
The final element corresponds to the upper right corner of the texture image.
_______________________________________________________________________
```
-  Locally checked that now everything is ok
Go over all the following points, and put an `x` in all …
=> Fix background image orientation

metainfo.xml, src/contour/Actions.cpp, src/contour/Actions.h, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/contour.yml, src/vtbackend/ControlCode.h, src/vtbackend/MatchModes.h, src/vtbackend/Screen.cpp, src/vtbackend/Sequence.cpp, src/vtbackend/Sequencer.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/TerminalState.h, src/vtbackend/primitives.h
Add first class support for executing each VT sequence interactively and see how the display's state changes.
For that, we've added a few new actions to bind to.
You see more if the indicator status line is currently shown, such as:
- you are currently in trace mode
- what is the next VT sequence to be executed.
Also, when the terminal is invoked from within another terminal (i.e. it is connected to a tty itself), then a each executed VT sequence will be logged onto stdout as well.
```yaml
input_mapping:
- { mods: [Control, Meta],  key: 'E',   mode: "~Trace",action: TraceEnter }
- { mods: [Control, Meta],  key: 'E',   mode: "Trace", action: TraceLeave }
- { mods: [Control, Meta],  key: 'N',   mode: "Trace", action: TraceStep }
- { mods: [Control, Meta],  key: 'F',   mode: "Trace", action: …
```
=> Initial implementation of a custom execution mode to interactively trace through the VT sequences.

metainfo.xml, src/vtbackend/Charset.cpp, src/vtbackend/Charset.h, src/vtbackend/Functions.h, src/vtbackend/Screen.cpp, src/vtbackend/Screen_test.cpp, src/vtbackend/Terminal.h, src/vtbackend/Terminal_test.cpp, src/vtbackend/test_helpers.h
Implements locking shifts `LS1` (`SO`) and `LS0` (`SI`).
The first commits are a little cleanup and only the last commit is the actual (trivial) implementation.
Some college was trying out Contour and realized that `SO`/`SI` wasn't being implemented. So here we go.
interactively:
```sh
printf "\033)0\x0e"; cat README.md ; printf "\x0f"
```
=> Implement locking shifts (S0 / SI)

metainfo.xml, src/vtbackend/ViCommands.cpp, src/vtbackend/ViCommands.h, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
Implemented by accident.
But it's actually useful :)
=> Improvements to vi-like normal mode: Add `P` to paste the clipboard with newlines stripped.

metainfo.xml, scripts/install-deps.ps1, scripts/install-deps.sh, src/vtbackend/ViCommands.cpp, src/vtbackend/ViCommands_test.cpp
Improves vi-mode motions `b` and `w` to better emulate what vim is doing. Plus adding tests for it (yay).
=> Improve vi-mode motions `b` and `w` to better emulate what vim is doing

metainfo.xml, src/vtbackend/Capabilities.cpp
=> terminfo: Changes terminfo entries `tsl`, `fsl` and `dsl` to make use of the host-writable statusline.

metainfo.xml, src/vtbackend/ViCommands.cpp, src/vtbackend/ViCommands.h, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
even more modal mode improvements. yay
=> [vi mode] add `B`, `W`, `E` and properly respect word boundaries in word text object (`iw` / `aw`).

metainfo.xml, src/vtbackend/Selector.cpp, src/vtbackend/Selector.h, src/vtbackend/Terminal.cpp, src/vtbackend/ViInputHandler.h, src/vtbackend/primitives.h
Enables the use of mouse while being in normal mode, to
=> Adds support for mouse in normal mode for selection and normal-mode's cursor placement.

.github/workflows/release.yml, scripts/install-deps.sh
soft revert to qt5 for the next release (or two?).
the qml pr will continue to focus being based on top of qt6 (rather than qt5).
=> install-deps script to use qt5 by default (again, and for now).

metainfo.xml, src/crispy/CMakeLists.txt, src/crispy/TrieMap.h, src/crispy/TrieMap_test.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/ViCommands.cpp, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
Refs #973
For better maintenance and easier extending the code with new features.
=> Refactoring modal input mode handler

metainfo.xml, src/vtbackend/Screen.h, src/vtbackend/ViCommands.cpp, src/vtbackend/ViCommands.h, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
I by accident wished to be able to set a mark in between of my very large command output, such that I can keep browsing up (in normal mode), but have a very quick way to jump back to the reading position I just was at.
There we go. Type in `mm` in normal mode to set/toggle the line mark at the current active cursor's line position. and then use `[m` and `]m` to jump up/down by line marks.
=> [vtbackend] Adds normal mode motion `mm` to toggle the line mark at the current active cursor position.

src/vtbackend/Screen.cpp
If there is a character at the right end of a line then putting tab before it shouldn't push it to next line.
To check
1. Run `tabs 2,4`
2. Run `printf 'a\t\t\t\t\tb'
Both a and b should be at the same line.
=> Adding tabstops before the right most end shouldn't push last character

metainfo.xml, src/crispy/TrieMap.h, src/vtbackend/ViCommands.cpp, src/vtbackend/ViCommands.h, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
Implements `f`, `F`, `t`, `T`, `;`, `,` for cursor move and yank operations. Refs #973.
=> Implements `f`, `F`, `t`, `T`, `;`, `,` for cursor move and yank operations.

metainfo.xml, src/contour/Config.cpp, src/contour/contour.yml, src/vtbackend/ColorPalette.h, src/vtbackend/RenderBufferBuilder.cpp, src/vtbackend/RenderBufferBuilder.h
I did it quickly actually because I keep searching for my cursor, and this helps finding it quicker. Hopefully helpful to others too (it's possible to disable).
=> Adds config entry `vi_mode_highlight` to color palette to highlight current line in non-insert mode

metainfo.xml, src/contour/TerminalSession.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h
With this patch, you can now actually use the `SendChars` action to send the (escaped) bytes RAW to the applications stdin, bypassing any further input mapping. This is what users might have expected anyways.
=> Fixes `SendChars` input acion to actually send the chars as-is to the standard input of the connected application.

docs/configuration/advanced/misc.md
```markdown
Add documentation to show how to make BS send ^H. This is the default for a vt220 IIRC.
```
```markdown
This is a "common" configuration item for people who connect to different systems.
```
I read it twice.
=> Documentation on mapping backspace to various chars

metainfo.xml, src/contour/Config.h, src/crispy/CMakeLists.txt, src/crispy/StrongHash.h, src/crispy/StrongLRUCache.h, src/crispy/StrongLRUCache_test.cpp, src/crispy/StrongLRUHashtable.h, src/vtbackend/Screen.h
Also adds compile time option: `STRONGHASH_USE_AES_NI` (default: ON)
@lhecker, just in case you are reading this, I did not find anymore what links you gave me last time we talked about it. But this seems to at least get it working on non crypto-enabed hardware (e.g. Raspberry Pi 4) :-)
In the long run, we might want to further refactor the code a bit to not depend on crypto hashes entirely for the usecases we are having, which are:
We are currently using hash keys for:
- texture atlas tiles for glyphs - we could simply use glyph keys here
- texture atlas tiles for box drawing glyphs - same as for regular text / emoji glyphs
- texture atlas tiles for image fragments (used for image display in the TE - this might only need some minor tweaks to not depend on crypto
- background image …
=> Allow building Contour on platforms not supporting hardware crypto extension (AES-NI)

.github/workflows/build.yml
Github updates its linux images from time to time and there is no need to update all of then manually
=> Remove apt update in ci

metainfo.xml, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h
Fixes mouse selection to only be initiated if actually meant to, i.e. in alt screen mode only if bypass-modifier was pressed 
This should ideally also fix #1017.
/cc @cqexbesd
=> Reworks initiating mouse selection in alt-screen mode.

metainfo.xml, src/contour/TerminalSession.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/ViCommands.cpp, src/vtbackend/Viewport.cpp, src/vtbackend/Viewport.h
Fixes #1019 by not doing auto-scroll for now.
I need to rethink that for what it's worth anyways.
=> Fixes mouse selection within scrolloff setting to not cause the viewport to jump anymore

src/crispy/App.cpp
```markdown
Add `endl` to `cout` lines when printing fatal error messages.
```
```markdown
Currently fatal error messages get shell prompts appended.
```
- I ran `countour debug` and made sure there was a new line.
=> Print \n after fatal error messages

metainfo.xml, src/vtbackend/ViCommands_test.cpp, src/vtbackend/ViInputHandler.cpp
Thanks @cqexbesd for reporting this to me.
This PR fixes motions like `yt ` but actually anything else that includes whitespace, like `f ` or `F ` etc.
Fixes #1037.
=> [vtbackend] VtInputHandler: Fixes vi-like motion `t{space}`.

src/contour/TerminalSession.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal_test.cpp
Fixes #1036. Sorry for the inconveniences.
This bug was introduced due to a recent refactor of mouse input handling, actually to reduce code complexity. Apparently I have removed too much, but it's working and a little bit tested now. :)
=> Fixes PasteSelection on mouse middle-click not working

src/crispy/base64.h
ref: https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes
the full build information in https://github.com/contour-terminal/contour/issues/1042#issue-1590545573
the `<cstdint>` header need to be included explicitly when you compile with GCC 13.
the detailed test information also in #1042 
=> Fix header dependency changes in gcc 13

metainfo.xml, src/crispy/times.h, src/vtbackend/Grid.cpp
When a scroll up is performed and there are not enough lines available to scroll we evict lines from ring buffer. But if user has set infinite history limit, then contour should allocate all required line before scrolling up.
Fixes #1040
=> Fixes scroll up when infinite history limit set, by allocating more

.github/workflows/build.yml, scripts/install-deps.sh
On newly installed ubuntu running `./scripts/install-deps.sh ` cause error 
` ./scripts/install-deps.sh : 47 curl not found` 
Also, while we are installing `ninja` on all platform `ubuntu` and `pop os` were missing
=> Update install-deps.sh script

metainfo.xml, src/vtbackend/Capabilities.cpp
zsh with stock oh-my-zsh seems to use `tsl` / `fsl` terminfo entries to set the window title. This broke however. Also due to one bad part in `tsl`. But generally we adapted `tsl` a bit to also clear the statusline and have it always start with an empty one, when using `tsl`.
To not mess with the users (using oh-my-zsh), another PR needs to follow-up that should add "programmatically showing the host programmable statusline" behind the permission wall (just like font change etc). So users can also configure it in the config file (per profile) how they want the terminal to react to such requests
=> Fixes terminfo `tsl` to how todays apps are using it (e.g. zsh) to simply set the window title.

src/contour/shell-integration/shell-integration.tcsh
```markdown
The code for tcsh shell integration was missing a round of escapes. This lead to unbalanced quotes and so an error from the shell when it was processed (e.g. when opening a new window).
I also swapped `\033` for `\e` as I think the later will be more readable to people using a C based shell.
```
```markdown
Previous code didn't work and printed errors when a new shell started.
```
I just ran it in my shell. 
=> Properly escape strings for tcsh

src/vtrasterizer/DecorationRenderer.cpp
Fixes https://github.com/contour-terminal/contour/issues/964 and https://github.com/contour-terminal/contour/issues/1065
=> Fix `int` to `unsigned` overflow conversion

.github/workflows/build.yml, .github/workflows/release.yml
this hopefully fixes the Windows build failures on CI.
=> Update VCPKG to latest release (currently used one yields 404 on some packages

metainfo.xml, src/vtbackend/ViCommands.cpp, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
example use is e.g.
- `vim`, `vam`
- `yim`, `yam`
=> Model mode: Adds text object `im` and `am` to select the range between two line marks

.github/workflows/build.yml, metainfo.xml, scripts/ci/notcurses-install-deps.sh, scripts/install-deps.sh, src/contour/CMakeLists.txt, src/vtpty/CMakeLists.txt, src/vtpty/LinuxPty.cpp
@cqexbesd noted that we're not logging to utmp. Using `libutempter` on Linux this is simply 2 calls to get it done.
=> Linux: Adds support for writing to utmp/wtmp

src/vtpty/CMakeLists.txt, src/vtpty/LinuxPty.cpp
I had to apply this in order to release on Flathub (Flatpak). Seems like libutempter isn't really possible (as of right now) on it. We can re-evaluate in the future, if there's any interest.
=> Avoid using utempter within Flatpak environment

metainfo.xml, src/vtbackend/RenderBufferBuilder.cpp, src/vtbackend/RenderBufferBuilder.h
Without this PR, search terms containing whitespaces where highlighted wrong in the render buffer output. This was due to the whitespace optimization. This PR disables the optimization due to the added complexity iff it would also need to handle proper search term match colorization when whitespaces were to be matched properly, too.
Closes #966
=> Fixes search term rendering highlighting for search terms containing whitespaces

.github/workflows/build.yml, .github/workflows/release.yml
Fixes #832.
Requires https://github.com/linuxdeploy/linuxdeploy-plugin-qt/issues/126 to be fixed **AND** merged first.
**Update:** I have given up on AppImage for the time being. I've added the one fix that was needed, but the catch is, that it doesn't work due to some internal unhandled exception. So we simply disable the whole idea of AppImage support until AppImage's linuxdeploy and its Qt-plugin become more stable.
=> Fixing AppImage package with respect to missing Qt QPA plugins.

metainfo.xml, src/vtrasterizer/TextRenderer.cpp
Closes #1115  
See https://freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_glyphslotrec
`bitmap_top` can  be negative, meaning that glyph direction is downward, this PR fixes the crash when contour can not display such glyphs, this is itself a hack since this is not how properly handle this case i suppose.
For example such figures still can be generated in contour
=> Invert direction for downwards glyphs

metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/text_shaper/font.h
Closes https://github.com/contour-terminal/contour/issues/1063
This PR partially implements inheritance of configuration file from proposal #1063 
Configuration profile is loaded based on `default_profile: ...... ` field and this profile is the only profile that must be properly configured. 
Following logic is implemented for loading configuration of profile:
* user defined `default_profile` is loaded based on provided configuration file,  if entry does not exist error will be emmited and default value providede by contour will be used
* each profile in the configuration file inherits all values from `default_profile` and if some of the field is provided inside configuration provided value for this profile will be used
example:  
```
profiles:
main:
.......................
inher:
shell: …
```
=> Inheritance of configuration profile based on default

src/contour/Config.cpp
At the moment font settings for bold and italic does not inherit font family from regular font.
This cause errors during rendering, this fix usage of same font family for regular bold and italic text
=> Fix font inheritance for profiles

cmake/PedanticCompiler.cmake
work around a bug in GCC on recent (GCC v13 at least) versions.
this at least affects Fedora 37 & 38.
=> [CMake] Work around GCC's false positives on -Wdangling-references

metainfo.xml, src/vtbackend/ViCommands.cpp, src/vtbackend/ViCommands_test.cpp
There is a weird behavior when entering insert vi mode if you were previously doing searches. 
When you search for a term an then switch to insert vi mode, the search term is not deleted.  So the search term continues being evaluated if you still using the terminal.
[vi-search-mode.webm](https://github.com/contour-terminal/contour/assets/43180519/4b7ef934-91d2-44a5-aec1-39b4801fe9fa)
```markdown
Clear search term when switch to insert vi mode
```
```markdown
Do not execute search term while using insert vi mode
```
- Manually
- Unit tests
=> clear search when switch to insert mode

metainfo.xml, src/contour/Config.cpp, src/contour/contour.yml, src/contour/display/TerminalWidget.cpp
Closes https://github.com/contour-terminal/contour/issues/1137
=> Delete dpi_scale option in configuration

metainfo.xml, src/vtrasterizer/Renderer.cpp
=> Fix glyphs overlap by creating spacing between tiles in Atlas

.github/workflows/build.yml
Fixes Github CI build pipeline.
There we create an artifact named `contour-ubuntu2204-tests` and use it twice, and delete it in each of their uses. That's obviously not working.
This PR defers deletion further to the back and deletes only once.
=> Fixes deletion of artifact contour-ubuntu2204-tests

scripts/install-deps.sh
Updating to latest main on ArchLinux builds but the resulting binary can't open a window due to:
```
Warning: QQmlApplicationEngine failed to load component ((null):0, (null))
Warning: qrc:/contour/ui/main.qml:30:5: Type Terminal unavailable (qrc:/contour/ui/main.qml:30, (null))
Warning: qrc:/contour/ui/Terminal.qml:41:5: Type FastBlur unavailable (qrc:/contour/ui/Terminal.qml:41, (null))
Warning: qrc:/qt-project.org/imports/Qt5Compat/GraphicalEffects/FastBlur.qml:5:1: Cannot load library /usr/lib/qt6/qml/Qt5Compat/GraphicalEffects/private/libqtgraphicaleffectsprivateplugin.so: (libQt6ShaderTools.so.6: cannot open shared object file: No such file or directory) (qrc:/qt-project.org/imports/Qt5Compat/GraphicalEffects/FastBlur.qml:5, (null))
```
Why is this change required? What problem does …
=> Add missing dependency for ArchLinux builds

.github/workflows/build.yml, scripts/ci/Xvfb-contour-run.sh, src/contour/display/TerminalWidget.cpp, src/contour/display/TerminalWidget.h, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtpty/ConPty.cpp, src/vtpty/ConPty.h, src/vtpty/LinuxPty.cpp, src/vtpty/LinuxPty.h, src/vtpty/MockPty.cpp, src/vtpty/MockPty.h, src/vtpty/MockViewPty.cpp, src/vtpty/MockViewPty.h, src/vtpty/Process.h, src/vtpty/Pty.h, src/vtpty/UnixPty.cpp, src/vtpty/UnixPty.h, src/vtpty/UnixUtils.h
this is a general alternative approach to #1150.
I tried to repro that be simply running `contour early-exit-threshold 0 true` where `true` is the command to execute within the contour TE instance, which exits instantly, thus, faster than the GUI needs time to fully initialize and have its first frame rendered.
This will not necessarily fix why notcurses-demo exits instantly **sometimes** on CI, but it helps avoiding the infinite wait loop.
=> Fixes GUI infinite loop on PTY closing faster than GUI initialization period

src/contour/Config.cpp
For me in release build QUrl can only deduce that the given path is a filesystem path if it prefixed with `file:`.
=> Prefixes file path with `file:` to fix bell in release build

.github/workflows/build.yml, .github/workflows/release.yml
Also, drop C++17 checks, since we default to C++20 in CMake already.
=> Build CI with C++20 minimum

src/contour/Config.cpp
@Yaraslaut if you look a few lines above, we'll already inherit bold from regular and italic from regular (as used to be), but somehow missed that line for bold+italic.
I'm adding this line back. Would you mind having a look over it?
=> Fixes bold_italic front not inheriting from regular

scripts/install-deps.ps1, scripts/install-deps.sh
Upgrading Catch2 to the latest available v2 release.
I highly doubt there will be any other v2 release ever, since v3 is out since quite some time already.
We can move to v3 as soon as it's available on all platforms (as in: we can make sure we can use v3 trivially on CI for all platforms we support so far).
=> Upgrade Catch2 from 2.13.7 to 2.13.10 (latest v2 release)

src/contour/Actions.h, src/crispy/ImageSize.h, src/crispy/StrongLRUHashtable.h, src/crispy/logstore.h, src/crispy/point.h, src/text_shaper/directwrite_shaper.cpp, src/text_shaper/font.h, src/text_shaper/font_locator.h, src/text_shaper/shaper.h, src/vtbackend/Functions.h, src/vtbackend/Image.h, src/vtbackend/Terminal.h, src/vtrasterizer/RenderTarget.h, src/vtrasterizer/TextureAtlas.h
At least my local dev box's MSVC + fmtlib version does not like the old way, which was not good anyways. But why was Github CI passing through?
=> Fixes bad use of fmtlib to also satisfy MSVC build

CMakeLists.txt, src/crispy/CMakeLists.txt, src/vtbackend/CMakeLists.txt, src/vtparser/CMakeLists.txt
This PR adds cmake target to run unit tests with `cmake --build build --target test`
Also, option for unit tests inherit value of `CONTOUR_TESTING`
=> Add cmake target for unit tests

src/contour/display/TerminalWidget.cpp, src/vtbackend/Line.cpp
After qml merge contour started to crash on text selection, this PR fix this crash. 
As for the reason why, @christianparpart  maybe you have idea ?
=> Fix crash on text selection

metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/contour.yml, src/vtbackend/Settings.h, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/TerminalState.h
Adding this feature solely for the Chuck Norris TE users or TE devs, that sometimes need to have a specific DEC mode permanently set or unset. Luckily this was apparently(?) also possible on original VTs as well (except that they didn't use YAML configurations for that).
At least [DECRQM](https://vt100.net/docs/vt510-rm/DECRQM.html) makes me think like that.
=> Add config option `profile.*.frozen_dec_modes`

metainfo.xml, src/contour/TerminalSession.cpp
closes #1199, The hyperlink uri already had the correct url format so, reencoding it again with QUrl was messing up the actual filename.
=> Fix file link opening

metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/contour.yml, src/vtbackend/Functions.h, src/vtbackend/Functions_test.cpp, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/Settings.h
=> Adds VT sequence DECSSCLS and properly handle DECSCLM

metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/contour.yml, src/contour/helper.cpp
On MacOS, using the Option key with another (e.g. A, B, ...), will result in other Unicode characters. It is typical to remap the Option key as if it would be an Alt key however.
This config option allows the remapping.
=> Adds config option `profile.*.option_as_meta` to allow remapping Option key to Alt on MacOS

.github/workflows/checks.yml, src/contour/Config.cpp
Somehow clang-format 15 started to giving errors while they dont exist
=> Fix formatting 

metainfo.xml, src/text_shaper/open_shaper.cpp, src/vtrasterizer/RenderTarget.cpp, src/vtrasterizer/TextRenderer.cpp
Closes https://github.com/contour-terminal/contour/issues/1022
Issue is that we were calling restrict
` void TextRenderer::restrictToTileSize(TextureAtlas::TileCreateData& tileCreateData) `
it can happen that tile is only partially larger and then we end up in such situation : 
```
[2023-09-23 07:17:58.886218542.886218] [vt.rasterizer] Inserting rasterized_glyph(0, 12x13+(-1, 13), rgb) (bbox 10x17, numCells 1) id 7034 render mode LCD Text yOverflow 0 yMin 4.
[2023-09-23 07:17:58.886221347.886221] [vt.rasterizer] Cutting off oversized RGB tile from 12x13 down to 10x21.
```
This cutting was copying empty rows
=> Avoid rendering empty space when cutting off overly wide LCD subpixel AA glyphs

scripts/install-deps.sh
`which` does not always return proper exit status 
See https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script
=> Better check inside install-deps.sh script

metainfo.xml, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/Screen_test.cpp
I found out about this problem simply because I moved to bufferline.nvim and was wondering why it didn't look so pleasing on the right side of the buffer tabs.
What was happening is, that vim was executing `CSI J` (ED) at the bottom of the alt screen and the for-loop for every subsequent line below the current line should be fully cleared. however , there is none, but the for-loop was overshooting, which was working, because it's a ring buffer. It was clearing the top-most line in the full grid buffer.
=> Fixes VT sequence ED (CSI J) when performed at the bottom line in alt screen

src/vtbackend/Screen.cpp
References @j4james comment in https://github.com/contour-terminal/contour/pull/1212/files#r1344674416
I hope I did understand you correctly there?
=> Match speeds for DECSSCLS as defined by old DEC VT1xx and VT2xx terminals

metainfo.xml, src/vtbackend/ViCommands.cpp
Fix error found by @Utkarsh-khambra  on vim `f` press. 
Issue is that when looking for next character to the right not always we can go to the next line
=> Fix infinite loop when next line does not exist

src/.clang-tidy, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/display/Blur.cpp, src/contour/display/Blur.h, src/contour/display/OpenGLRenderer.cpp, src/contour/display/TerminalWidget.cpp, src/contour/helper.h, src/crispy/read_selector.h, src/text_shaper/directwrite_shaper.cpp, src/text_shaper/font.h, src/text_shaper/fontconfig_locator.cpp, src/text_shaper/mock_font_locator.cpp, src/text_shaper/open_shaper.cpp, src/vtrasterizer/Renderer.cpp
Add clang-tiy checks for naming of data mamebers inside struct/class
I was confused previouslu and was thinking that `ClassMemberCase` will check naming convention for the class/struct members, but it only checks `static` members. 
This PR adds clang-tidy checks for the names of private and public members
=> Check naming of class/struct members

metainfo.xml, src/contour/Actions.cpp, src/contour/Actions.h, src/contour/Config.cpp, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/contour.yml
This patch adds the `OpenSelection` action, which can be used to quickly open a link in the buffer. With an appropriate word selector, one can select an URL and open it with a keybind.
It is a variation of this patch:
https://st.suckless.org/patches/open_copied_url/, which I use daily to quickly open URLs in chat, mails, diffs, etc.
I have not tested it, but it should work with other URIs, like file:// and such.
I've also fixed a minor behavior I encountered while developing this patch: By default, the Config will upper() the keybind used when it is a simple key, but for simple Alt+Key binds (in my case, I use Alt+o for this feature), the event sent to the terminal is Alt+o (Alt+6F), while the configuration stores Alt+O (Alt+4F). I've corrected this behavior, which might break stuff; but …
=> feat: Add OpenSelection action, and honor case in the configuration bindings

.clang-format, .gitignore, docs/configuration/profiles.md, docs/vt-extensions/color-palette-update-notifications.md, metainfo.xml, mkdocs.yml, src/contour/CMakeLists.txt, src/contour/Config.cpp, src/contour/Config.h, src/contour/ContourGuiApp.cpp, src/contour/ContourGuiApp.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/TerminalSessionManager.cpp, src/contour/TerminalSessionManager.h, src/contour/contour.yml, src/contour/display/TerminalWidget.cpp, src/vtbackend/ColorPalette.h, src/vtbackend/Functions.h, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/TerminalState.cpp, src/vtbackend/VTWriter.h, src/vtbackend/primitives.h
Closes #604 
https://github.com/contour-terminal/contour/assets/56763/ea4b5867-defc-489b-bdf2-9aa635275ff0
=> Use color scheme based on OS system dark/light mode preferences

metainfo.xml, src/contour/Config.cpp, src/contour/helper.cpp, src/crispy/flags.h, src/vtbackend/InputGenerator.cpp, src/vtbackend/InputGenerator.h, src/vtbackend/InputGenerator_test.cpp
drop-out commits from PR #1250.
closes #150 
not just adding keys, but also removing numpad keys, because they were never used in Contour and it seems like I cannot disambiguate them from within Qt API anyways?
also contains a little commit on extending the new `flags<T>` API
=> minor keyboard input changes: adding more key mappings in preparation to future work

src/contour/Config.cpp, src/vtbackend/InputGenerator.cpp
Move logging of config into configLog so users do not see them as errors if something is missing, for example in the case
when user defined only one key to change default behavior 
Refs https://github.com/contour-terminal/contour/issues/1125
=> Move config errors in config log

README.md
```markdown
`git clone git clone` is not a valid command as it has too many arguments.
```
```markdown
Build documentation for windows was wrong, specifically the git clone command had `git clone git clone`.
```
`N/A`
=> fix(readme): correct windows git clone command

docs/vt-extensions/csi-u-extended-keyboard-protocol.md, metainfo.xml, mkdocs.yml, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/helper.cpp, src/contour/helper.h, src/crispy/flags.h, src/vtbackend/Functions.h, src/vtbackend/InputGenerator.cpp, src/vtbackend/InputGenerator.h, src/vtbackend/InputGenerator_test.cpp, src/vtbackend/MockTerm.h, src/vtbackend/Screen.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h
Initial support for extended CSIu.
Well, it works for shortcuts as much as neovim is concerned. I have some open minor questions and the problem that Qt does not expose ALL information the way I need it, but it's already an improvement and works backwards compatible. :)
=> Add Keyboard protocol extension `CSI u`

src/vtbackend/InputGenerator.cpp, src/vtbackend/ViInputHandler.cpp
=> Various fixes that lately broke master

.github/workflows/build.yml
We check shell exit on both 20.04 and 22.04 versions
=> Fix download-artifact name

.github/workflows/build.yml
Atempt to make github actions complete in some reasonable time for pull requests 
Longest actions 
* Windows 20 min
* Fedora 16-17 min
While we can move fedora builds to freebsd build so we check them only after merge, windows build is more essential and unfortunately slow
=> Make github actions faster for PRs

scripts/install-deps.ps1, scripts/install-deps.sh, src/vtbackend/CMakeLists.txt
* Catch2 for fedora is now used from package system (since we do not support older Fedora)
* termbench library is updated to latest master (containing only packaging improvements itself)
=> some more dependency packaging improvements/updates

src/contour/TerminalSession.cpp, src/contour/display/TerminalWidget.cpp, src/contour/display/TerminalWidget.h, src/contour/helper.cpp, src/contour/ui.template/Terminal.qml.in
Fixes the bug mentioned in #1271 with regards to font resize also causing the window to resize.
no changelog entry needed, because this bug was introduced after last release (related to QML merge)
=> Fixes font resize causing window to resize

metainfo.xml, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/vtpty/ConPty.cpp, src/vtpty/ConPty.h, src/vtpty/MockPty.cpp, src/vtpty/MockPty.h, src/vtpty/MockViewPty.cpp, src/vtpty/MockViewPty.h, src/vtpty/Process.h, src/vtpty/Process_unix.cpp, src/vtpty/Process_win32.cpp, src/vtpty/Pty.h, src/vtpty/UnixPty.cpp, src/vtpty/UnixPty.h
PTY handle can still be open by e.g. another process (caused by commands like `long running command &` in a typical shell.
Closes #866.
=> Fixes terminal session not being terminated when the process terminated but PTY handle still open

src/vtbackend/InputGenerator.cpp, src/vtbackend/InputGenerator.h
Reviving keypad/numpad key handling in `InputGenerator`.
This still misses the Qt frontend part, but that was never there. This PR at least brings back the backend part and ensures that (once working for the Qt part), we're having it all automatically for the backend again.
=> Revive input mapping of keypad/numpad keys

src/contour/Config.cpp, src/contour/contour.yml, src/contour/helper.cpp, src/contour/helper.h, src/vtbackend/ViInputHandler.cpp
Kinda hard to test and verify blindingly - while not having a keyboard that is having a keypad, but I think this is going into the right direction.
The problem of keypad not working was introduced by implementing CSIu, which strongly differenciates between numbers and numbers typed in from numpad.
Now, also fixes #1325!
NB: No changelog needed because this problem was introduced post last release and only affects CSIu (new)
=> Improve Numpad input mapping (relevant for CSIu protocol)

src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/crispy/CMakeLists.txt, src/crispy/utils.cpp, src/crispy/utils.h, src/vtpty/SshSession.cpp, src/vtpty/UnixPty.cpp, src/vtpty/UnixPty.h
We're having two events to watch out for. PTY may be closed and the process may exit. One does not imply the other. We are about to consider the PTY session to be finished whenever one of those two conditions arise, no matter which one comes in first. Sometimes (e.g. quick exit, e.g. just spawning `/bin/true` as shell) the process will terminate so fast, that we didn't even fully initialize the GUI. We need to properly terminate on that condition as well as expect that both events (PTY closed **and** process terminated) happens at the same time. Both events call `onClosed()`. This is why i've guarded it with a mutex to avoid concurrent calling (which happened before).
=> pragmatic fix of shell quick exit

src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/helper.cpp, src/contour/helper.h, src/crispy/flags.h, src/vtbackend/InputBinding.h, src/vtbackend/InputGenerator.cpp, src/vtbackend/InputGenerator.h, src/vtbackend/InputGenerator_test.cpp, src/vtbackend/InputHandler.h, src/vtbackend/Settings.h, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
- polish flags API to be more generally usable
- adds `logging.tags` to contour configuration (this is more useful for debugging on Windows)
- refactor vtbackend's Modifiers API to make use of recently introduced `flags<T>` API
- attempt to fix AltGr-use on Windows (also when CSIu input protocol is used)
=> Fix CSIu for Ctrl+Alt (AltGr) on Windows

src/crispy/flags.h, src/vtbackend/CellFlags.h, src/vtbackend/CellUtil.h, src/vtbackend/Grid.cpp, src/vtbackend/Grid.h, src/vtbackend/Grid_test.cpp, src/vtbackend/InputGenerator.h, src/vtbackend/Line.cpp, src/vtbackend/Line.h, src/vtbackend/Line_test.cpp, src/vtbackend/RenderBufferBuilder.cpp, src/vtbackend/Screen.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal_test.cpp, src/vtbackend/VTWriter.cpp, src/vtbackend/ViCommands.cpp, src/vtbackend/cell/CompactCell.h, src/vtbackend/cell/SimpleCell.h, src/vtrasterizer/DecorationRenderer.cpp, src/vtrasterizer/TextRenderer.cpp
streamlining flags to avoid unnecessary code bloat.
should make the code also more streamlined.
=> Adapting CellFlags and LineFlags to new `flags<T>`

metainfo.xml, src/contour/ContourGuiApp.cpp, src/contour/ContourGuiApp.h
On Wayland, there's no such thing as WM_CLASS (X11), but a user can use the `app_id` to identify and group Application windows. However, Qt sets that not via QCoreApplication::setApplicationName but rather uses QCoreApplication::setOrganizationDomain's information in reverse name order.
Closes #1336.
=> Fixes setting window class (`app_id`) on Wayland

scripts/install-deps.ps1, scripts/install-deps.sh
It's currently just a tag, but if it all goes well, we should make it a release in libunicode, and depend on THAT instead, so we have an officiel libunicode release version we can point downstream maintainers to. :)
=> Update libunicode to latest

src/vtbackend/Terminal.h
from fmt release page :  
https://github.com/fmtlib/fmt/releases/tag/10.1.0
```
Disallowed passing temporaries to make_format_args to improve API safety by preventing dangling references.
```
closes https://github.com/contour-terminal/contour/issues/1350
=> Fix fmt compilation.

src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/Screen_test.cpp, src/vtbackend/Sequencer.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/TerminalState.cpp, src/vtbackend/TerminalState.h
This bug was introduced when trying to fix semantics of margins in a6e49038507223ac2a9137db6f6a72936f79f312.
Thanks @Marenz for figuring this out.
=> Fix the use of margins within (host writable) statusline

scripts/install-deps.ps1, scripts/install-deps.sh
such that future contour release depends on a fixed release of boxed-cpp (1.1.0)
=> Bump boxed-cpp to version 1.1.0

src/contour/TerminalSession.cpp, src/contour/display/TerminalDisplay.cpp, src/contour/display/TerminalDisplay.h, src/contour/helper.cpp, src/vtpty/UnixPty.cpp
this is mostly affecting HiDPI screens, anything with a non-standard DPI setting.
no changelog entry needed, because it was introduced with the QML rework
Closes #1299.
=> Fix window resize events not respecting content scale 

scripts/install-deps.sh
The script used to say that FreeBSD is unsupported despite there
being an explicit case for it.
Fix by correcting the casing.
=> [scripts] Fix OS misdetection in install-deps.sh for FreeBSD

metainfo.xml, src/contour/TerminalSession.cpp, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/Terminal.cpp
Closes #1377.
This PR also does a mini cleanup around DECSCUSR's implementation.
=> Changes VT sequence `DECSCUSR`'s default parameter reset to user-configured cursor style

metainfo.xml, src/vtbackend/InputGenerator.cpp
When `CSI > 1 u` was used to enter CSI u mode with DisambiguateEscapeCodes flag set, then (e.g. on German keyboard layout), a double quote is produced with Shift + 2, which generate the double quotes: `"`
This should not needed to be disambiguated (unless explicitly requested)
Closes #1373
=> Fix CSIu encoding of shift modifier produced characters

src/contour/contour.yml
I assume the proper to do this is to comment out the key, which works without error messages.
I initially tried leaving the key with no value (based on the comment) but that caused `[error] Invalid frozen_dec_modes entry.`. Using a value of `{}` worked but seemed more confusing than anything.
=> contour.yml: fix incorrect default for frozen dev modes

metainfo.xml, src/text_shaper/open_shaper.cpp
Some fonts do not provide separate files for regular and bold weight but use the same, this make impossible to distinguish this two possibilities when comparing file paths and font size
=> Fix collision of bold and regular font files

src/contour/helper.cpp
This is probably related to building using Qt 5 rather than Qt 6.
This should fix #1384's comment on failing to run Contour on RHEL. I think maybe it's building against Qt5 rather than Qt6 on that platform, and that Qt5 us inducing somewhat different execution order on Contour-side. 🤔
=> Attempting to fix assertion failure when running in RHEL Linux

metainfo.xml, src/contour/TerminalSession.h, src/contour/helper.cpp
Closes https://github.com/contour-terminal/contour/issues/1360
Qt backend sends a lot of mouse events on scroll with touchpad, this PR introduce time restiction between mouse events that we apply to terminal, this must affect only scroll on touchpads since all other manuall events can not be separated in time for such small duration as 50 ms
=> Accumulate scroll distance instead of immediately trigger scroll

docs/input-modes.md
Markdown has a lot of weird obscure corners; TIL there's a specific markup for inline code that can contain backticks.
=> docs: fixed markup for backticks text object

metainfo.xml, src/contour/helper.cpp, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h
Refs #1275, #1268.
When writing a wide character, the next cell should be reset with the current SGR plus an additional flag to indicate that the next cell is a continuation cell of its left sibling cell.
But when overwriting such a character, the next cell must be cleared again, too, regardless of the new width.
=> Fixes screen destruction on sibling cells when overwriting wide characters

metainfo.xml, src/contour/helper.cpp
=> Fix Alt+WheelEvents not captured correctly

src/contour/TerminalSession.cpp
Adds quotes around characters inside input log so we can see space ther
=> add quotes around chars for input logging

scripts/ci/Xvfb-contour-run.sh, src/vtbackend/Terminal.cpp
It looks like actions are working well now, even though nothing significant has been changed, apart from the logging level for these tests. Locally, I notice that notucrses-demo can fail from time to time due to events like terminal resizing. I think it is sufficient for us to have this PR merged at the moment and if needed to investigate further how to deal with it. for example to build notcurses from source inside actions as @christianparpart  few times proposed 
Closes https://github.com/contour-terminal/contour/issues/1402
=> Fix notcurses github action

metainfo.xml, src/vtbackend/InputGenerator.cpp
=> Fix legacy keyboard input protocol not reporting non-Alt modifier

cmake/Version.cmake, src/contour/CMakeLists.txt
Fixes a long standing issue I had with windows installations, which is, seeing a very old version number (the one from the very first install), which does not reflect the actual installation.
=> Properly handle installation/upgrade by specifying product/upgrade GUID for Windows installer

metainfo.xml, src/crispy/flags.h
Closes https://github.com/contour-terminal/contour/issues/1408
Also, fixes my locall build with libssh support, see target names: https://github.com/libssh2/libssh2/pull/1104
=> Fix Windows alt/control key modifiers

metainfo.xml, src/vtpty/SshSession.cpp, src/vtpty/SshSession.h
=> Allow password retry on priv-key auth and try with empty password first automatically

.github/workflows/build.yml
MacOS packaging is failing lateley in actions, this PR is atempt to fix it
See https://github.com/actions/runner-images/issues/7522
=> Fix packaging for osx inside actions

metainfo.xml, src/contour/TerminalSession.cpp, src/crispy/defines.h, src/crispy/utils.h
=> Fix thread safety issue on mouse move event handling

src/crispy/StackTrace.cpp
Compile abi calls only if header is found
=> Check abi define

metainfo.xml, src/vtbackend/Image.cpp, src/vtbackend/Screen.cpp, src/vtbackend/SixelParser.h, src/vtbackend/primitives.h, src/vtpty/PageSize.h, src/vtrasterizer/Renderer.cpp
Refs https://github.com/contour-terminal/contour/issues/1049
Issue was with atlas size, magic factor of 3 is enough for 2k resolution to not get this bug 
I am not sure about 4k resolution though since i can test only on 2k, so @christianparpart  maybe you can give it a try?
=> Some small corrections and fix automatic adjustement of atlas size

scripts/install-deps.sh
```markdown
Add `--needed` to `pacman` command line for Arch Linux in `install-deps.sh`
```
```markdown
Currently `install-deps.sh` re-installs required packages every time you run the script, assuming you already have the dependencies.
```
- tries it on my machine - seems to work
=> Don't reinstall packages every time

src/contour/CMakeLists.txt
Fix call to add qt resources, see documentation for `qt_add_resources` https://doc.qt.io/qt-6/qt-add-resources.html
Refs https://github.com/contour-terminal/contour/issues/1466 
i was getting same error
=> Fix qt resources call in cmake

docs/vt-extensions/save-and-restore-sgr-attributes.md, metainfo.xml, mkdocs.yml, src/vtbackend/Functions.h, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/Screen_test.cpp
Closes #1473 but does not implement #1473. This is because XTPUSHSGR / XTPOPSGR are conceptionally plain wrong.
However, having the ability to save and restore all SGR attribs at once is a really good idea that does suffice the general use-cases.
Having a stack only works around poor application implementations. This includes pushing specific SGR attribs alone.
This is why SGRSAVE and SGRRESTORE are simply saving and restoring the all the SGR attributes, including colors, and all other SGR attributes.
The chosen VT sequences intentionally conflict with XTPUSHSGR / XTPOPSGR because:
1. the trivial case is semantically the same (no parameters given)
2. providing parameters is fundamentally wrong
3. adding yet another stack is fundamentally wrong
=> Add SGRSAVE and SGRRESTORE VT sequences to save and restore SGR state

.github/ISSUE_TEMPLATE/Bug_Report.yml, .github/mock-font-locator.yml, .github/workflows/build.yml, README.md, docs/configuration/advanced/misc.md, docs/configuration/advanced/mouse.md, docs/drafts/terminal-emulators.md, docs/features.md, docs/index.md, docs/install.md, metainfo.xml, src/contour/CMakeLists.txt, src/contour/contour.yml, src/contour/display/TerminalDisplay.cpp, src/contour/helper.cpp, src/text_shaper/fontconfig_locator.cpp, src/vtrasterizer/FontDescriptions.h, src/vtrasterizer/TextRenderer.cpp
The Macintosh operating system underwent many name changes over the years,
from being nameless to "System" to "Mac OS" to "OS X" to "macOS".
But at no point in time was it ever called "OS/X" :-)
=> Replace all occurrences of OS/X

metainfo.xml, src/contour/contour.desktop
Closes https://github.com/contour-terminal/contour/issues/1423
Mime type changed to one used in Konsole, also keywords deleted, see https://github.com/KDE/konsole/blob/61264c1917770102a85123d388528f2bcacfd960/desktop/konsolerun.desktop#L4
=> Update desktop entry

.github/workflows/build.yml, metainfo.xml
Refs https://github.com/contour-terminal/contour/issues/955
Closes https://github.com/contour-terminal/contour/issues/586
=> AppImage packaging for Qt6 and Ubuntu 22.04

src/contour/Actions.h, src/contour/Config.cpp, src/contour/Config.h, src/contour/ConfigDocumentation.h, src/text_shaper/font.h
Fix bug with generation of few entries in the config
=> Update of config generation

metainfo.xml, src/contour/display/TerminalDisplay.cpp
this is only noticeable on displays that have a DPI scaling (of != 1) configured
=> Fixes `CSI 8 ; (COLS) ; (ROWS) t` to resize the terminal with respect to High-DPI

src/contour/TerminalSession.cpp, src/vtbackend/CMakeLists.txt, src/vtbackend/Cursor.h, src/vtbackend/Hyperlink.h, src/vtbackend/MockTerm.h, src/vtbackend/RenderBufferBuilder.cpp, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/ScreenBase.h, src/vtbackend/Screen_test.cpp, src/vtbackend/Sequencer.cpp, src/vtbackend/StatusLineBuilder.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/Terminal_test.cpp, src/vtbackend/ViCommands.cpp, src/vtbackend/ViCommands_test.cpp, src/vtbackend/primitives.h, src/vtpty/ConPty.cpp, src/vtpty/ImageSize.h, src/vtpty/MockPty.cpp, src/vtpty/MockViewPty.cpp, src/vtpty/UnixPty.cpp
cleaning up some old'ish technical debt.
Closes #1484.
=> Refactoring Terminal's internal state storage

src/contour/Config.h, src/contour/display/TerminalDisplay.cpp, src/contour/helper.cpp, src/contour/helper.h, src/vtbackend/InputHandler.h, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/Terminal_test.cpp, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
Add boxed types for window margins and input handling
=> Introduce boxed types for margins and handling of input

src/crispy/result.h, src/crispy/result_test.cpp
I intentionally did not make it 100% compatible (i.e. void value type is not really supported, only partial code exists). I mostly decided to not implement that part due to lag of free time and lag of current use-cases (as of right now). :)
=> Adapt result-type to latest changes in std::expected<T, E> API as found on cppreference.com

src/contour/Config.cpp, src/contour/Config.h
Small refactor of config creation.
=> Small refactor to generalize config creation

metainfo.xml, src/vtpty/SshSession.cpp, src/vtpty/SshSession.h
Closes https://github.com/contour-terminal/contour/issues/1447
=> Make user feedback during ssh login less verbose

metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/ConfigDocumentation.h, src/contour/TerminalSession.cpp, src/vtbackend/Selector.h, src/vtbackend/Selector_test.cpp, src/vtbackend/Settings.h, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h
This PR implements additional step during word selection that uses `extended_word_delimiters` configuration entry.
Closes https://github.com/contour-terminal/contour/issues/1023
=> Add extended_word_selection

src/vtbackend/CMakeLists.txt, src/vtbackend/Screen.h
Closes https://github.com/contour-terminal/contour/issues/1229
=> Get rid of LIBTERMINAL_CACHE_CURRENT_LINE_POINTER

src/vtrasterizer/DecorationRenderer.cpp
This PR makes a small refactor if DecorationRendere.cpp and allows underline thickness to be equal to 1.
I think that this can close https://github.com/contour-terminal/contour/issues/663
And refs https://github.com/contour-terminal/contour/issues/1242
=> Allow thickness of underline to be 1

src/contour/Actions.cpp, src/contour/Actions.h, src/contour/Config.cpp, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/contour.yml, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h
Closes https://github.com/contour-terminal/contour/issues/1023
PR adds action to trigger selection with custom delimiters
@cqexbesd you can add following entry in config file:
```
- { mods: [Control],        mouse: Left,        action: CreateSelection, chars: " " }
```
=> Add action to set custom delimiters for selection

metainfo.xml, src/vtbackend/InputHandler.h, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
Closes https://github.com/contour-terminal/contour/issues/1468
Restrict forwarding of some of the events while in normal mode:
* mouse press 
* keys like 'Enter', 'ESC', 'Tab', 'Shift'
=> Restrict forwarding of some of the inputs while in normal mode

metainfo.xml, src/contour/CMakeLists.txt, src/contour/Config.h, src/contour/ContourGuiApp.cpp, src/contour/contour.yml
Contour's app icon in the window title bar (on KDE plasma on Wayland) was showing a default W-icon rather than our own one. This fixes it.
=> Fixes application window icon on (KDE) Wayland

src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/bench-headless.cpp, src/vtpty/ConPty.cpp, src/vtpty/ConPty.h, src/vtpty/MockPty.cpp, src/vtpty/MockPty.h, src/vtpty/MockViewPty.cpp, src/vtpty/MockViewPty.h, src/vtpty/Process.h, src/vtpty/Pty.h, src/vtpty/SshSession.cpp, src/vtpty/SshSession.h, src/vtpty/UnixPty.cpp, src/vtpty/UnixPty.h
overall code cleanups
- [vtpty] Make Pty::ReadResult more intuitive to use (less cryptic)
=> Code cleanups

metainfo.xml, src/vtbackend/ViInputHandler.cpp
=> Add some more missing vi input motions, such as `y$`, `o$`, and many others as initiated by `y` and `o` 

metainfo.xml, src/text_shaper/coretext_locator.mm, src/text_shaper/shaper.cpp
Closes #1533.
Adds implementation of font fallback discovery on MacOS.
Requires at least MacOS 13.1
=> Implement font fallback on MacOS

metainfo.xml, src/vtbackend/ViCommands.cpp
I think this is a sane default behavior that allows you to investigate the output from the command
Closes https://github.com/contour-terminal/contour/issues/808
=> Stop scroll when switching to normal mode

docs/configuration/colors.md, metainfo.xml, src/contour/Config.cpp, src/contour/ConfigDocumentation.h, src/vtbackend/ColorPalette.h, src/vtbackend/Terminal.cpp
Closes https://github.com/contour-terminal/contour/issues/1528
This PR adds customization of indicator status line colors for different modes.
Unfortunately it breaks present configuration for inactive status line
=> Add mode dependent configuration for indicator statusline colors

.github/workflows/build.yml, cmake/presets/os-windows.json, metainfo.xml, src/vtpty/Process_win32.cpp
Some apps on Windows can't handle a TERM variable that they do not know about. There is also no way to resolve terminfo db entries on Windows neither. So simply don't export it, such that apps won't get confused.
=> Do not export TERM env var when using ConPTY (on Windows)

metainfo.xml, src/contour/ui.template/Terminal.qml.in
Do not spawn bell sound when bell is playing, it allows to handle bell signals much faster in the case when the bell is constantly spawning
=> Improves handling of constant bell sound spawning

metainfo.xml, src/vtbackend/ViCommands.cpp
Closes https://github.com/contour-terminal/contour/issues/1448
PR fixes selection for w/W vim motions
=> Fix selection of w/W vim motions

cmake/ContourThirdParties.cmake
fix following error
```
CMake Warning at cmake/ContourThirdParties.cmake:38 (find_package):
By not providing "Findboxed_cpp.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"boxed_cpp", but CMake did not find one.
Could not find a package configuration file provided by "boxed_cpp" with
any of the following names:
boxed_cppConfig.cmake
boxed_cpp-config.cmake
Add the installation prefix of "boxed_cpp" to CMAKE_PREFIX_PATH or set
"boxed_cpp_DIR" to a directory containing one of the above files.  If
"boxed_cpp" provides a separate development package or SDK, be sure it has
been installed.
Call Stack (most recent call first):
cmake/ContourThirdParties.cmake:130 (HandleThirdparty)
CMakeLists.txt:129 (include)
```
Cannot compile on …
=> ContourThirdParties.cmake: fix boxed-cpp detection

cmake/ContourThirdParties.cmake, scripts/install-deps.ps1, scripts/install-deps.sh
Bump of boxed-cpp and  code update to use new functionality of creation boxed types without extra tags
Some info about compiler support: https://github.com/NVIDIA/stdexec/issues/1143#issuecomment-1937482532 
tl;dr
we need gcc-14 and we see that windows build is failing
=> Bump of boxed-cpp and code update

.github/workflows/build.yml
This PR:
* Fix freebsd github action
* update fedora 39 -> 40
* build notcurses only for ubuntu 24.04
* openbsd action run only on master
* static build action run on master and release
* macos action install certificate while on master or release
=> Fix and update github actions

src/contour/contour.desktop
fix `Error in file "/usr/local/share/applications/org.contourterminal.Contour.desktop": "" is an invalid MIME type ("" does not contain a subtype)` at install
=> fix error, "" is an invalid MIME type ("" does not contain a subtype)

metainfo.xml, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal_test.cpp
PR fixes a bug when copying a selection of a wrapped line. 
Previously new-line was inserted without the need when copying the selection span across few grid-line, when they represent  one logical lines that is wrapped due to terminal size
=> Fix copy of multi-line selection

mkdocs.yml
Add path to generated key-mapping.md file inside mkdocs
=> Fix path to key-mapping docs

metainfo.xml, src/vtbackend/Screen.h
MSVC was giving me runtime errors when i was opening julia, with the message that iterators can not be comparable
I beleive that this PR  closes https://github.com/contour-terminal/contour/issues/883
=> Fix line corruption on windows

src/vtbackend/Line.h
Without this, it built failed.
```
[31/124] /usr/bin/g++ -DCONTOUR_STACKTRACE_ADDR2LINE=1 -DFMT_HEADER_ONLY=1 -DHAVE_BACKTRACE -DHAVE_BACKTRACE_SYMBOLS -DHAVE_CXXABI_H -DHAVE_DLADDR -DHAVE_DLFCN_H -DHAVE_DLSYM -DHAVE_EXECINFO_H -DHAVE_SYS_SELECT_H -DHAVE_UNWIND_H -DLIBTERMINAL_LOG_TRACE=1 -DLIBTERMINAL_NAME=\"contour\" -DLIBTERMINAL_VERSION_MAJOR=0 -DLIBTERMINAL_VERSION_MINOR=4 -DLIBTERMINAL_VERSION_PATCH=4 -DLIBTERMINAL_VERSION_STRING=\"0.4.4\" -DVTPTY_LIBSSH2=1 -I/builddir/build/BUILD/contour-terminal-0.4.3.6442-build/contour-c895cde8b29f1c6a4dc9db3ca1c670e34d0337f1/src -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS …
```
=> Fix build for fmt 11

metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/ContourApp.cpp, src/contour/ContourGuiApp.cpp, src/contour/ContourGuiApp.h, src/crispy/times.h
Closes https://github.com/contour-terminal/contour/issues/1125
Now user can query list of entries that are missing from the config file via
`contour info config`, i am not sure what will be the better place for this action, so i am open for suggestions @christianparpart
=> Get list of entries that are missing in config file

metainfo.xml, src/contour/Config.cpp, src/contour/helper.cpp
Closes https://github.com/contour-terminal/contour/issues/1578
Shift+Tab is Qt::Key_Backtab (https://doc.qt.io/qt-5/qt.html#Key-enum) we should send it as a key, not as a character
=> Send backtab as a key

.github/workflows/build.yml, scripts/install-deps.sh
at least my Fedora 40 on my new Linux laptop instantly started to complain on a fresh Fedora install. I sadly don't seem to remember what exactly the error message was ;(
Also, added a commit to streamline all upload-artifact actions to v4 (we had 2 at v3 and v2 still)
=> install-deps.sh: Flip curl/wget priority to favor curl over wget, because at least Fedora 40 Linux seems to complain on wget

docs/configuration/profiles.md, metainfo.xml, src/contour/Config.cpp, src/contour/ConfigDocumentation.h, src/vtbackend/ColorPalette.cpp, src/vtbackend/ColorPalette.h, src/vtbackend/Line.cpp
Refs https://github.com/contour-terminal/contour/issues/1285
PR adds few predefined color palettes, values are taken from https://github.com/Gogh-Co/Gogh/tree/master/themes
and supported themes are:
contour, monokai, one-dark, one-light, gruvbox-light, gruvbox-dark, solarized-light, solarized-dark, papercolor-light, papercolor-dark.
in config user can specify both single colorscheme or as a map like:
```
colors: contour
```
or 
```
colors:
light: monokai
dark: contour
```
=> Add predefined color palettes

cmake/ContourThirdParties.cmake, metainfo.xml, scripts/install-deps.ps1, scripts/install-deps.sh
=> Update libunicode to support Unicode 16.0.0

src/contour/Config.cpp
Closes https://github.com/contour-terminal/contour/issues/1599
@herrhotzenplotz  I hove this is sufficient to find terminfo files on freebsd
=> Add few BSD specific locations during terminfo loading

.github/workflows/build.yml
Disable openbsd build 
@jg1uaa I disable github action to build openbsd since it is not working at the moment because c++ library is to old to support std::format 
Latest release that does not require std::format is https://github.com/contour-terminal/contour/releases/tag/v0.5.0.7168 but you need to have fmt version lower than 11
=> Disable openbsd action

.github/pull_request_template.md
```markdown
Commit 7ebb1899f577cae422f1362db531d02468a0eda2 moved the location of `CONTRIBUTING.md`. This PR adjusts sources to changes.
```
```markdown
broken link in pull request
```
=> Update contributing reference

src/contour/ContourGuiApp.cpp, src/contour/helper.h
=> Tiny code cleanup for macOS builds to not require manual keyboard modifier swapping

metainfo.xml, src/contour/helper.cpp
funny enough, mouse wheel pixel data depends on High DPI setting of your monitor. Well... May make sense.
=> Fixes mouse wheel scrolling on High-DPI screens feeling too slow

metainfo.xml, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/TerminalSessionManager.cpp, src/contour/TerminalSessionManager.h, src/contour/display/TerminalDisplay.cpp, src/contour/display/TerminalDisplay.h, src/contour/helper.cpp, src/contour/ui.template/main.qml.in, src/vtbackend/Terminal.h
it took me a while to figure out that fraction scaling on KDE Plasma (probably due to Wayland) is problematic. However, this PR still cleans up a lot and reliably produces the expected columns x lines page size on initial window spawn.
Fractional scaling on at least Wayland (KDE?) should be fixed later on its own.
=> simplify, cleanup, and improve window size/resize handling

docs/configuration/indicator-statusline.md, src/contour/Config.h, src/contour/TerminalSessionManager.h, src/vtbackend/StatusLineBuilder.cpp, src/vtbackend/StatusLineBuilder.h, src/vtbackend/Terminal.h
Improve UI/UX a bit of tabs feature's statusline:
- have the active tab's color customizable
- teh tabs textual representation in the statusline must not jump around in spacing, based on what tab is active (due to ` [N] ` vs ` N `.
- refs: #1634 (would benefit from it)
=> Add styling-capability for active tab in Tabs view in statusline

metainfo.xml, src/vtrasterizer/TextRenderer.cpp
Closes https://github.com/contour-terminal/contour/issues/1603
Some fonts want underscore character to be below grid cell completely, we can allow
=> Do not crop symbol that is completely below cell

src/contour/Config.h
Transform camelCase of names  inside c++ structures to snake_case that is used inside config files 
Refs https://github.com/contour-terminal/contour/issues/1622
=> Transform camelCase into snake_case for docs

metainfo.xml, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/ui.template/Terminal.qml.in
Closes https://github.com/contour-terminal/contour/issues/1198
=> Request permission on big paste

metainfo.xml, src/vtbackend/InputGenerator.h, src/vtbackend/InputGenerator_test.cpp
Fixes macOS specific handling of the input
-  Option used as a Control modifier, to allow Option-Left[Right] jumps between words in the shell
=> Fix macOS specific key handling

.github/static/DockerQt
Updated static build to use qt 6.8
=> Update qt version for static build

metainfo.xml, src/vtbackend/CMakeLists.txt, src/vtbackend/JumpHistory.cpp, src/vtbackend/JumpHistory.h, src/vtbackend/Screen.cpp, src/vtbackend/Terminal.h, src/vtbackend/ViCommands.cpp, src/vtbackend/ViCommands.h, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
Closes https://github.com/contour-terminal/contour/issues/1101
=> Implement vi mode jumps

docs/vt-extensions/color-palette-update-notifications.md
Although sometimes our OSes can truly can be an "operaging" system, I suspect "operating" was intended.
=> Fix typo in "operating system"

.github/workflows/build.yml
Disable github action for fedora since they are failing outside of compilation and we build we recent compilers in another actions
=> Disable fedora github action

docs/CONTRIBUTING.md, docs/configuration/advanced/renderer.md, docs/configuration/key-mapping.md, docs/demo/size_indicator.md, docs/drafts/daemon-mode.md, docs/drafts/grid-redesign.md, docs/input-modes.md, docs/install.md, docs/internals/index.md, docs/internals/text-stack.md, docs/vt-extensions/save-and-restore-sgr-attributes.md, docs/vt-extensions/synchronized-output.md
Spelling fixes in `docs` directory.
Pedantic change: fixing spelling in MkDocs documentation.
=> docs(spelling): fix typos in documentation

README.md, docs/features.md
Update links for synchronized rendering and buffer capture in `README.md` and adjust links in `MkDocs` documentation to match `*.md` syntax used by other links.
Current links as of now simply redirect to the repository's main GitHub page/README. + Remove hard-coded domain in MkDocs links.
=> docs(fix): update old wiki links to point to the MkDocs pages

metainfo.xml, src/vtbackend/CellUtil.h, src/vtbackend/Terminal_test.cpp
Change the cell logic to reset underline style flags on a new style being applied to match the behavior of other terminals.
Example of the change affecting output:
```sh
printf '\033[4:3mAB\033[4:2mCD\033[4:1mEF\033[0mGH\n'
```
Before change:
After change:
Change behavior to match other terminal emulators like libvte, KDE Konsole, and WezTerm.
Example of Gnome Terminal on Ubuntu 24:
```sh
$ ./build/linux-clang-release/src/vtbackend/vtbackend_test
Randomness seeded to: 3112360726
Starting resize to 3x2
===============================================================================
All tests passed (3703 assertions in 198 test cases)
```
=> Fix underline style reset

metainfo.xml, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
Fix bugs:
* search string was not preserved when switching from search prompt into normal mode
* when switching from insert into normal mode search string were not cleared
=> Improvements of the search mode

src/contour/TerminalSessionManager.cpp, src/contour/TerminalSessionManager.h, src/contour/display/TerminalDisplay.cpp, src/contour/helper.cpp, src/vtrasterizer/TextClusterGrouper_test.cpp
Refs https://github.com/contour-terminal/contour/issues/1632
PR:
* Fixes bug with crash on resize and tab switching, way to reproduce: 
* resize the window
* create new tab
* exit
* create new tab (size will be wrong)
* try to return the the previous tab (crash happening)
* Implements wrapping of tab index when switching to left/right
* Implements preservation of tab cwd on new tab spawn
=> Some Improvements to the tabs

docs/vt-extensions/color-palette-update-notifications.md
I noticed that contour is no longer the only terminal supporting dark/light mode notifications:
both Ghostty and Kitty also support it.
Adoption is also documented for synchronized output so it seems very natural
to also add it for this.
- `n/a` I have updated (or added) the documentation accordingly.
- `n/a` I have added tests to cover my changes.
=> docs: Add adoption state for dark/light mode notifications

metainfo.xml, src/contour/TerminalSessionManager.cpp, src/contour/display/TerminalDisplay.cpp
Fix crash with resize and tab switching, we notice this bug on systems with scaled UI (specifically macOS, but bug can appear on other systems as well)
=> Fix error with wrong terminal size during tab switch

metainfo.xml, src/vtbackend/InputGenerator.cpp
Closes https://github.com/contour-terminal/contour/issues/1685 
Solution is somewhat ugly, I am open for better one @christianparpart  :) 
but we need to preserve behavior for sending it as a key for https://github.com/contour-terminal/contour/issues/1578
=> Fix backtab pty.output generation

metainfo.xml, src/contour/Actions.cpp, src/contour/Actions.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/TerminalSessionManager.cpp, src/contour/TerminalSessionManager.h, src/contour/ui.template/Terminal.qml.in
Improves usability of tab switching and tab closing a bit.
Also adds new action `SwitchToPreviousTab` to bind some input mapping to, to easily switch between two tabs that are not necessarily next to each other.
I also refactored the code around it for better clarity.
=> [contour] Improve tab switch handling and add `SwitchToPreviousTab`

metainfo.xml, src/contour/Actions.cpp, src/contour/Actions.h, src/contour/Config.cpp, src/contour/ConfigDocumentation.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/TerminalSessionManager.cpp, src/contour/TerminalSessionManager.h, src/contour/ui.template/Terminal.qml.in
initial support of moving tabs
@Yaraslaut I think we should give `TerminalSession` access to its owning list of tabs (`TerminalSessionManager` currently).
Maybe the name isn't the best, when thinking of tabs alone. In the long term, we might think of a tree data structure in order to implement tiling-like splits/pane views.
So whatever the DS / API will be, a leaf node (like a terminal session) should always have access to its parent node. What do you think? IMHO, this could also simplify the logic in the QML side (something I failed to revive in my head today)
Changes:
closes #1692
closes #1691
=> Further improvements to tabs handling (add MoveTabToLeft / MoveTabToRight / MoveTabTo actions)

metainfo.xml, src/vtbackend/Screen.cpp
fixes broken replies to decrqss (and possibly more, but i only noticed while testing that)
tested by calling decrqss
=> add missing separators

metainfo.xml, src/vtbackend/Capabilities.cpp, src/vtbackend/Capabilities_test.cpp
With a little bit of help, I've got `msgcat --color=test` to output true colors in the "hue/saturation" section, which looks partly like this:
While this one better exposes the colors supported by Contour, we still have a remaining problem. gettext (the package providing `msgcat` executable) is heavily hardcoded down to xterm :vomiting_face:), so we need to make it pretend we are exterm by symlinking `c/contour` terminfo file to `x/xterm-contour`.
We should probably talk to the gettext guys to make their heuristic less xterm-centric.
=> Change `colors` terminfo entry from 256 up to 32767 colors

metainfo.xml, src/vtbackend/ViCommands.cpp, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
=> Implement CenterCursor vi motion

metainfo.xml, src/vtbackend/InputGenerator.cpp
Closes https://github.com/contour-terminal/contour/issues/1701
=> Add control codes for Control+(5,6,7,8) input

src/vtbackend/InputGenerator.cpp
Thanks to @j4james, I've mapped the Ctrl + key handling a little bit more streamlined as it is documented in DEC STD 070, page 6-170.
refs #1702.
=> InputGenerator: refactor Ctrl+key input mapping

src/contour/TerminalSession.cpp, src/contour/TerminalSessionManager.cpp, src/contour/TerminalSessionManager.h, src/contour/ui.template/Terminal.qml.in
1) Avoid qml signal handling 
2) Handle action per key press without repeating, so you can not spawn new tabs when holding key-binding for it
=> Switch to TerminalSessionManager everywhere and fix small bug

src/contour/Actions.h, src/contour/TerminalSession.cpp, src/crispy/utils.h
Make some of the actions repeatable
=> Make some actions repeatable

metainfo.xml, src/contour/helper.cpp
Closes https://github.com/contour-terminal/contour/issues/1707
We need to relax the condition on the number of codepoints that can be inserted at once, since IME allows inserting more than one  glyph at a time.
=> Relax condition for codepoints size for IME

metainfo.xml, src/vtrasterizer/TextRenderer.cpp
Closes https://github.com/contour-terminal/contour/issues/1603
Some fonts position characters to underflow, for example char `p` so we should not crop such characters as long as they are not exceeding cell size
=> Do not crop underflow glyphs if they fit in cell size height

.github/ISSUE_TEMPLATE/Bug_Report.yml
ARM64 and AArch64 are the same thing. Some platforms and tools prefer using this or that name for it. Similarly, in many cases especially on Linux, different distributions and ecosystems use `amd64` instead of `x86-64` or `x86_64` to refer to what is essentially the same thing.
For example, Ubuntu uses `amd64`, `arm64`, and `i386` in the package names; see for example: https://launchpad.net/ubuntu/noble/+package/gcc-12-base.
Running the stock util command `arch` on Mac says `arm64` or `i386` (even for 64-bit Mac Intel builds: try running `arch -x86_64 zsh` to spawn an emulated version of the shell and then call `arch` inside, it will still say `i386`!), but the Linux `arch` command (and, by that logic, `uname`) reports `aarch64` and `x86_64` for the ARM vs. PC line.
=> [GitHub] Fix bug report template drop-down selection elements

docs/CONTRIBUTING.md, docs/vt-extensions/vertical-line-marks.md
Noticed the first when reading the terminal extensions documentation, and
noticed the second when reading the contributing guide.
```markdown
- **vertical-line-marks.md: Fix typos in ZSH integration docs**
- **CONTRIBUTING.md: Fix typo: s/bare with us/bear with us/**: https://www.merriam-webster.com/dictionary/bear%20with#phrases
```
```markdown
Fixes two typos.
```
- N/A
=> Fix a couple of typos

.github/workflows/build.yml, docs/configuration/colors.md, metainfo.xml, src/contour/Config.cpp
- Adapted from #1743.
- Fixes the colorscheme config loading for the indicator status line to include `default` and `insert_mode` sections.
- Updates the examples in the docs to include all 5 sections, as well as removing the unused `indicator_statusline_inactive` section.
- Closes #1737.
- The docs (currently) state that 5 sections may be configured under the `indicator_statusline` section of the config: `default`, `inactive`, `insert_mode`, `normal_mode`, and `visual_mode`. These changes reflect that claim.
- See https://github.com/contour-terminal/contour/pull/1743#issuecomment-2770891575 for further context.
- Built locally and verified by removing portions of the config to see changes.
- Before: ![Before](https://github.com/user-attachments/assets/724ccaaf-46e7-4b12-9224-613398e3cd20) …
=> Fix indicator statusline default and insert mode loading

docs/vt-extensions/color-palette-update-notifications.md
:wave:
This is a super minor change - I've been jumping around on which branch I'm using for mode 2031 support in Helix so I've made an issue now to track it properly https://github.com/helix-editor/helix/issues/13281.
(Thanks for creating the extension btw, it's very handy :slightly_smiling_face:)
=> docs: Switch Helix mode 2031 tracker to an issue

src/text_shaper/shaper.cpp
- **just a patch to compile rbg**
- **added a patch to metainfo.xml**
this is not the required solution to #1750 just a workaround that works for me.
I added this PR for visibility, maybe someone else will need it
I don't think it should be merged
Fixes: #1750
Just to overcome compilation error
Just compiled
- [-] I have read the [**`CONTRIBUTING`**](https://github.com/contour-terminal/contour/blob/master/docs/CONTRIBUTING.md) document in my spoken language, and understand the terms
- [-] I have updated (or added) the documentation accordingly.
- [-] I have added tests to cover my changes.
- [-] I have gone through all the steps, and …
=> a workaround to issue #1750

CMakeLists.txt
Allow configure compilation to use native flag, since libunicode can benefit from simd native implementation
=> Let configure compilation with -march=native flag

docs/configuration/colors.md, metainfo.xml, src/contour/Config.cpp
Fall through when configuring preset palette.
Allows tweaking preset configuration later in the yaml
Enables, for example, under `color_schemes`:
```
one-light:
word_highlight_other:
foreground: CellForeground
background: CellBackground
foreground_alpha: 1.0
background_alpha: 1.0
```
Enables tweaking preset color schemes.
It allows users to change part of the configuration when selecting a preset one.
I ran it locally
`docs/configuration/colors.md` was updated with the new ability
=> allow preset colors tweaks

src/contour/Config.cpp, src/vtbackend/Selector.cpp, src/vtpty/Process_unix.cpp, src/vtpty/Process_win32.cpp, src/vtrasterizer/RenderTarget.cpp, src/vtrasterizer/utils.cpp
- Standardize vector declarations to either `vector` or `std::vector` per-file
- For each file containing 'using namespace std':
- Analyze existing usage patterns of std types
- Convert all vector declarations to match the prevalent style:
* Use unqualified `vector` if majority usage omits std::
* Use fully qualified `std::vector` if majority explicitly scopes types
- Maintains internal consistency within each file
- Preserves existing coding patterns and style preferences
- No functional changes - purely stylistic refactoring
=> Refactor: Unify vector declaration style in files with 'using namespace std"

src/contour/ContourGuiApp.cpp
Added an if staement to support constexpr usage
Fixes: https://github.com/contour-terminal/contour/issues/1774
Without it pedentic does not work
compiled
=> Fixed compilation error by spliting to an if statement
