src/IncludeFilesystem.h, src/contour/Config.cpp
Just making an empty config file so the yml library doesn't throw if the file doesn't exist.
=> Adding in a small check to see if the config file exists and creating it

.github/workflows/osx.yml, README.md, cmake/FilesystemResolver.cmake
=> Enable OS/X CI

src/contour/TerminalWindow.cpp, src/contour/contour.yml, src/crispy/Atlas.h, src/crispy/text/Font.cpp, src/crispy/text/Font.h, src/crispy/text/FontLoader.cpp, src/crispy/text/FontLoader.h, src/crispy/text/TextRenderer.cpp
=> Font: Gracefully handle errors in loading glyphs by glyph index.

src/terminal/Grid.cpp
=> Fixes history.limit not being respected.

src/contour/Config.h, src/terminal/Screen.cpp, src/terminal/Sequencer.cpp, src/terminal/Sequencer.h, src/terminal/SixelParser.h, src/terminal/SixelParser_test.cpp
=> Changes sixel palette size default and related.

src/terminal/InputGenerator.cpp, src/terminal/InputGenerator.h, src/terminal/Screen.cpp, src/terminal/ScreenEvents.h, src/terminal/Terminal.cpp, src/terminal/Terminal.h
=> Fixes hard-reset not resetting keyboard/mouse input states.

Changelog.md, src/terminal/Screen.cpp, src/terminal/Screen.h, src/terminal/Screen_test.cpp, src/terminal/Sequencer.cpp, src/terminal/Sequencer.h
Fixes #238. In order to get  https://github.com/dankamongmen/notcurses/issues/1582 (on Contour) rolling. :-)
=> Adds VT sequence DECRQM (or better: finishes it)

src/crispy/App.cpp, src/crispy/debuglog.h
=> Workaround for MSVC compilation.

src/contour/TerminalWindow.cpp
Fixes #271 
it's hard to see the different on my WM, but hopefully better on yours.
=> [contour] Fixes scrollbar `hidden` mode to also resize terminal widget area to maximum size.

src/contour/Config.cpp, src/crispy/escape.h, src/terminal_renderer/DecorationRenderer.cpp
Closes #251 
With this patch, currently you have do append `debug error` in order to see the new error messages.
=> [contour] Report on missing config keys.

scripts/release-ppa.sh, src/contour/CMakeLists.txt, src/contour/ContourApp.cpp
Not sure about these:
https://github.com/contour-terminal/contour/blob/4fadc98738650e4b499e90ebdf1ab560ee002672/scripts/release-ppa.sh#L92
https://github.com/contour-terminal/contour/blob/4fadc98738650e4b499e90ebdf1ab560ee002672/src/contour/CMakeLists.txt#L97
=> Fixing the remaining links

CMakeLists.txt, TODO.md, src/contour/ContourApp.cpp, src/contour/TerminalSession.cpp, src/crispy/App.cpp, src/crispy/CMakeLists.txt, src/crispy/StackTrace.cpp, src/crispy/StackTrace.h, src/terminal/Terminal.cpp
=> Adds stacktrace printing SEGV handler.

cmake/ThirdParties.cmake
And update yaml-cpp to latest.
=> Add EXCLUDE_FROM_ALL to all third-parties

Changelog.md, TODO.md, src/contour/Config.cpp, src/contour/contour.yml, src/terminal_renderer/BoxDrawingRenderer.cpp, src/terminal_renderer/BoxDrawingRenderer.h, src/terminal_renderer/CMakeLists.txt, src/terminal_renderer/TextRenderer.cpp, src/terminal_renderer/TextRenderer.h, src/terminal_renderer/utils.cpp, src/terminal_renderer/utils.h, test/box-drawings.sh
=> pixel perfect box drawing

cmake/ThirdParties.cmake
=> [CMake] Changing the order of CPMAddPackage() calls fixes YAML's SEGV

src/crispy/CLI.cpp, src/terminal/Image.h
moved out of GIP branch to be on master early.
=> random stuff

src/terminal_renderer/BoxDrawingRenderer.cpp
any straight line was looking to thin/mushy due to super-sampling anti-aliasing.
=> Fixes bad visuals on some box drawing primitives.

README.md, src/contour/Config.cpp, src/terminal/Terminal.cpp, src/terminal/pty/UnixPty.cpp, src/text_shaper/font.h, src/text_shaper/open_shaper.cpp
Fixes #343 and some others not mentioned in any ticket.
=> various fixes (including for #343)

src/crispy/CMakeLists.txt, src/crispy/LRUCache.h, src/crispy/LRUCache_test.cpp
Initial work on an LRU-cache to be used for any kind of caching (glyph, text shaping, hyperlinks, images).
=> LRU cache API and some initial uses

src/text_shaper/directwrite_shaper.cpp
* Do not search all the fonts returned by `fontCollection->GetFontFamilyCount`. Use `fontCollection->FindFamilyName` instead.
* Fallback to "Consolas" if no exact font can be found.
* Fallback to "en-US" locale if no exact locale can be found.
=> Improve load_font in DWrite shaper

Changelog.md, src/contour/Config.cpp, src/contour/contour.yml, src/contour/helper.cpp, src/terminal_renderer/Renderer.cpp, src/terminal_renderer/TextRenderer.h
=> config option for selecting text shaping engine

Changelog.md, src/contour/Config.cpp, src/contour/contour.yml, src/terminal_renderer/Renderer.cpp, src/terminal_renderer/TextRenderer.h, src/text_shaper/CMakeLists.txt, src/text_shaper/directwrite_shaper.cpp, src/text_shaper/directwrite_shaper.h, src/text_shaper/font.h, src/text_shaper/font_locator.h, src/text_shaper/fontconfig_locator.cpp, src/text_shaper/fontconfig_locator.h, src/text_shaper/open_shaper.cpp, src/text_shaper/open_shaper.h, src/text_shaper/shaper.h
=> font file resolving extracted into its ownfont_locator API

src/text_shaper/directwrite_shaper.cpp
It should try to find fallback fonts *only* if the current font doesn't contain the correct glyphs.
=> Fix DWrite shaper fallback logic

cmake/Modules/MacOSXBundleInfo.plist.in, src/contour/CMakeLists.txt
This will bring HiDPi window chrome in contour on macOS. 
See https://doc.qt.io/qt-5/highdpi.html
=> Added dedicated bundle plist for macOS

src/contour/helper.cpp, src/contour/helper.h, src/contour/opengl/OpenGLRenderer.cpp, src/contour/opengl/OpenGLRenderer.h, src/contour/opengl/TerminalWidget.cpp, src/contour/opengl/TerminalWidget.h, src/terminal_renderer/RenderTarget.h
Factors some logic out of OpenGL `TerminalWidget` to make it easier to also support other rendering backends, such as Vulkan or Software.
=> [contour] OpenGL widget related refactors.

src/contour/TerminalSession.cpp, src/terminal/Screen.cpp, src/terminal/Terminal.cpp, src/terminal_renderer/DecorationRenderer.cpp, src/terminal_renderer/DecorationRenderer.h
=> Fixes at least rounding issues in underline decorations and line overall thickness

src/terminal/Parser.h, src/terminal/ParserEvents.h, src/terminal/Parser_test.cpp, src/terminal/Sequencer.h, src/terminal/bench-headless.cpp
=> [terminal] Parser: Fixes APC handling and adds some basic interface for handling it.

Changelog.md, src/contour/opengl/TerminalWidget.cpp
This might hopefully also fix #407.
=> [contour] Do not force OpenGL ES on Linux.

Changelog.md, src/contour/TerminalSession.cpp, src/terminal/InputGenerator.cpp, src/terminal/Terminal.cpp, src/terminal/Terminal.h
Fixes CPU load issue on mouse-move as mentioned in #407.
=> [terminal] Fixes CPU load going up on mouse move inside terminal window.

src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/helper.cpp, src/terminal/InputGenerator.cpp, src/terminal/InputGenerator.h, src/terminal/Terminal.cpp, src/terminal/Terminal.h
=> more mouse-move event performance optimizations

Changelog.md, src/contour/Config.cpp
=> [contour] Fixes configuring a custom shell on OS/X.

Changelog.md, src/terminal/Screen.cpp
=> [terminal] Changes DECSDM to reflect changes in xterm-369 to match behaviour of real VT340.

Changelog.md, src/terminal/Screen.cpp, src/terminal/Sequencer.cpp
Addresses at least the XTSMGRAPHICS SetValue issue of #422.
=> Fixes XTSMGRAPHICS SetValue for Sixels at least.

Changelog.md, src/contour/Config.h, src/contour/TerminalWindow.cpp, src/contour/contour.yml
Addressing point 2 in #422.
Not sure these values are nice, maybe 4k screen-ish default? Not sure yet.
=> Changes (Sixel) image default size limits to 1920x1200.

cmake/ThirdParties.cmake
=> Update FreeType and HarfBuzz

CMakeLists.txt, cmake/PedanticCompiler.cmake, src/terminal/Screen.cpp, src/terminal/Screen_test.cpp
Fixes  #488 (bug found via STL checkers).
=> Fixes captureBuffer call

src/crispy/LRUCache.h, src/terminal_renderer/BoxDrawingRenderer.cpp
Thanks to #488 I now even found a second culprit.
And the other commit further improves `LRUCache` performance.
=> 1 fix & 1 smile & 1 improvement

CMakeLists.txt, Changelog.md, src/contour/Actions.cpp, src/contour/Config.cpp, src/contour/ContourApp.cpp, src/crispy/App.cpp, src/crispy/App.h, src/crispy/CLI.h, src/crispy/utils.h, src/terminal/InputGenerator.cpp
=> Adds `contour license` CLI command.

Changelog.md, src/terminal/Parser.h, src/terminal/ParserEvents.h, src/terminal/Parser_test.cpp, src/terminal/Sequencer.h, src/terminal/bench-headless.cpp
=> Fixes crash caused by PM and SOS.

Changelog.md, src/contour/Config.cpp, src/contour/contour.yml, src/text_shaper/font.h, src/text_shaper/open_shaper.cpp
=> Adds support for font feature settings.

Changelog.md, src/contour/Config.cpp, src/contour/contour.yml, src/contour/opengl/TerminalWidget.cpp, src/contour/opengl/TerminalWidget.h, src/terminal/Color.h, src/terminal/Grid.h, src/terminal/Screen.cpp, src/terminal/Terminal.cpp, src/terminal/Terminal.h, src/terminal/Terminal_test.cpp, src/terminal_renderer/CursorRenderer.cpp, src/terminal_renderer/CursorRenderer.h, src/terminal_renderer/Renderer.cpp, src/terminal_renderer/Renderer.h
=> Improves text cursor rendering and extends cursor configuration accordingly (#526).

Changelog.md, debian/control
=> [CI] updated control file for debian based distros

scripts/install-deps.sh, scripts/install-git-hooks.sh, src/contour/CMakeLists.txt
=> Fix/548 feedback, take 2

Changelog.md, src/contour/Config.cpp, src/contour/opengl/TerminalWidget.cpp, src/terminal/Cell.h, src/terminal/Screen.cpp, src/terminal/Screen.h, src/terminal/Sequencer.cpp, src/terminal/Sequencer.h
=> random improvements, making notcurses happy (as always) ^^

README.md, scripts/install-deps.sh
=> Apply install-deps.sh script changes from 0.2.x branch for enabling GNU/Debian support. Thanks @ssta.

scripts/install-deps.sh, src/crispy/ring.h, src/terminal/Grid.cpp
No changelog entry needed. It's only broken on master.
=> Fixes SD VT sequences for fullscreen-scrolls

Changelog.md, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/helper.cpp, src/terminal/InputGenerator.cpp, src/terminal/InputGenerator.h, src/terminal/Screen.cpp, src/terminal/Sequencer.cpp, src/terminal/Sequencer.h, src/terminal/Terminal.cpp, src/terminal/Terminal.h, src/terminal/primitives.h
=> Adds SGR-Pixels support (VT sequence `SM ? 1016 h` / `RM ? 1016 l`).

Changelog.md, src/terminal/Capabilities.cpp, src/terminal/Capabilities.h, src/terminal/Screen.cpp, src/terminal/Screen_test.cpp
=> [terminal] Screen: Fixes XTGETTCAP response to string requests and invalid numeric requests.

src/contour/Config.h, src/terminal/InputGenerator.h, src/terminal/Screen.h
On arch the compiler fails on missing formatter, this PR should provide them
=> Add formatter

Changelog.md, src/terminal/Grid.cpp, src/terminal/Screen_test.cpp
Fixes #593 
Also adds missing unit test cases.
Thanks @ninjalj for the report and the really minimal reproduction example. That helped a lot!
=> [terminal] Fixes `SU` in combination with `DECLRM` (#593).

src/terminal_renderer/TextureAtlas.h, src/text_shaper/fontconfig_locator.cpp, src/text_shaper/open_shaper.cpp
=> Fixes a crash with regards to font's average width calculating when no US-ASCII glyphs are found.

Changelog.md, src/contour/CaptureScreen.cpp, src/contour/CaptureScreen.h, src/contour/ContourApp.cpp, src/contour/TerminalSession.cpp, src/crispy/utils.h, src/terminal/Functions.h, src/terminal/Parser.h, src/terminal/ParserEvents.h, src/terminal/Parser_test.cpp, src/terminal/Screen.cpp, src/terminal/Screen_test.cpp, src/terminal/Sequencer.cpp
=> [contour] Fixing capture-buffer feature.

.github/workflows/build.yml
hopefully fixing the SSH error message.
=> [Github CI] bump freebsd-vm action from 0.1.5 to 0.1.6

src/contour/opengl/TerminalWidget.cpp, src/contour/opengl/TerminalWidget.h
@whisperity can you confirm that this is fixing your initial window-size problem?
=> [contour] Fixes initial window size on Ubuntu 18.04 (/old Qt).

src/contour/ScrollableDisplay.cpp
Fixes #620 
See also discussion at the above issues.
=> (#620) Fix white border bug

src/terminal/Grid.cpp, src/terminal/Grid.h, src/terminal/Line.h
=> Fixes resize bug / scrollback history rotation

Changelog.md, src/contour/opengl/OpenGLRenderer.cpp, src/terminal_renderer/ImageRenderer.cpp, src/terminal_renderer/RenderTarget.cpp, src/terminal_renderer/RenderTarget.h, src/terminal_renderer/TextureAtlas.h
=> Fixes abort if displaying sixel and resizing font

Changelog.md, src/terminal/Process_unix.cpp
Now this should fix the other issue as raised in #647.
Closes #647.
=> Fixes fallback shell spawning

Changelog.md, src/terminal/RenderBufferBuilder.cpp, src/terminal/Terminal.cpp
=> Fixes selection being wrongly rendered when viewport is scrolled.

src/contour/TerminalSession.cpp, src/terminal/InputGenerator.cpp
=> improve pasting from clipboard when data is non-textual

scripts/ci/Xvfb-contour-run.sh, src/contour/Config.cpp, src/contour/ContourGuiApp.cpp, src/contour/TerminalSession.cpp, src/crispy/CLI.cpp, src/terminal/ViInputHandler.cpp
=> Trying to fix CLI.

.clang-format, Changelog.md, src/contour/BackgroundBlur.cpp, src/contour/ContourApp.cpp, src/contour/TerminalSession.cpp, src/contour/main.cpp, src/crispy/StrongHash.h, src/crispy/StrongLRUCache.h, src/crispy/StrongLRUHashtable.h, src/terminal/CMakeLists.txt, src/terminal/Process.h, src/terminal/Process_unix.cpp, src/terminal/Process_win32.cpp, src/terminal/bench-headless.cpp, src/terminal/pty/ConPty.cpp, src/terminal/pty/ConPty.h, src/terminal/pty/LinuxPty.cpp, src/terminal/pty/LinuxPty.h, src/terminal/pty/MockPty.cpp, src/terminal/pty/MockPty.h, src/terminal/pty/MockViewPty.cpp, src/terminal/pty/MockViewPty.h, src/terminal/pty/Pty.cpp, src/terminal/pty/Pty.h, src/terminal/pty/UnixPty.cpp, src/terminal/pty/UnixPty.h, src/terminal/pty/UnixUtils.h, src/text_shaper/directwrite_analysis_wrapper.h, src/text_shaper/directwrite_shaper.cpp
Makes use of Linux-specific system calls (epoll, eventfd) in order to ideally improve performance "slightly". ;-)
=> [terminal] Adds specialized implementation for Linux PTY.

src/contour/Config.cpp, src/contour/Config.h, src/contour/ContourGuiApp.cpp, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/TerminalWindow.cpp, src/contour/contour.yml, src/crispy/App.cpp, src/crispy/utils.h, src/terminal/Terminal.h
Hi,  writing back cells to terminal is still not correct.
=> [DRAFT] Resuming sessions

Changelog.md, src/terminal/Capabilities.cpp
=> Adds E3 capability for clearing scrollback and screen

src/terminal/RenderBufferBuilder.cpp
=> makeColors correctly handles `CellFlags::Hidden`

scripts/install-deps.ps1, scripts/install-deps.sh, src/contour/ContourGuiApp.cpp, src/terminal/Line.cpp, src/terminal/Line.h, src/terminal/Line_test.cpp, src/terminal/Parser-impl.h, src/terminal/ParserEvents.h, src/terminal/Parser_test.cpp, src/terminal/RenderBuffer.h, src/terminal/RenderBufferBuilder.cpp, src/terminal/RenderBufferBuilder.h, src/terminal/Screen.cpp, src/terminal/Screen.h, src/terminal/Sequence.h, src/terminal/Sequencer.cpp, src/terminal/Sequencer.h, src/terminal/Terminal_test.cpp, src/terminal/bench-headless.cpp, src/terminal_renderer/Renderer.cpp, src/terminal_renderer/TextRenderer.cpp, src/terminal_renderer/TextRenderer.h
early merge of safe code changes.
prerequisite for #692.
=> prep-works for VT text processing PR

src/terminal/Line.cpp, src/terminal/Line.h, src/terminal/Terminal.cpp
=> Resets all empty cells on receiving `GraphicsRendition::Reset`

src/terminal/Parser-impl.h, src/terminal/RenderBuffer.h, src/terminal/RenderBufferBuilder.cpp, src/terminal/RenderBufferBuilder.h, src/terminal/Screen.cpp, src/terminal/Terminal_test.cpp, src/terminal_renderer/BackgroundRenderer.cpp, src/terminal_renderer/BackgroundRenderer.h, src/terminal_renderer/DecorationRenderer.cpp, src/terminal_renderer/DecorationRenderer.h, src/terminal_renderer/Renderer.cpp, src/terminal_renderer/Renderer.h, src/terminal_renderer/TextRenderer.cpp, src/terminal_renderer/TextRenderer.h
=> [terminal] Introduce RenderLine struct for ideally more efficient rendering of trivial lines.

.github/workflows/checks.yml, src/contour/CaptureScreen.cpp, src/contour/Config.cpp, src/crispy/CLI.cpp, src/crispy/StackTrace.cpp, src/crispy/StrongLRUHashtable.h, src/terminal/Grid_test.cpp, src/terminal/InputGenerator.cpp, src/terminal/Line.h, src/terminal/Parser-impl.h, src/terminal/Process_unix.cpp, src/terminal/Screen.cpp, src/terminal/Screen.h, src/terminal/Screen_test.cpp, src/terminal/SixelParser.cpp, src/terminal/SixelParser_test.cpp, src/terminal/Viewport.h, src/terminal/pty/UnixPty.cpp, src/terminal_renderer/Renderer.cpp, src/text_shaper/directwrite_shaper.cpp
Let's do some QA house-cleaning.
=> Fixing remaining compiler warnings.

src/terminal/Terminal.cpp
=> Selection snaps to end of line, when it reaches last filled cell

src/contour/TerminalSession.cpp
GTK3 apps seems to add CRLF line endings on copying text into clipboard. I just replaced those CRLF to LF before sending it pty.
=> Normalizes `\r\n` and `\r` from clipboard to `\n` for non windows platforms

src/contour/ContourGuiApp.cpp, src/contour/TerminalSession.cpp
=> Keep working directory same when new terminal is spawned

Changelog.md, README.md, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/contour.yml, src/terminal/Viewport.cpp, src/terminal/Viewport.h
=> Adds vim-like `scrolloff` feature to normal/visual mode cursor movements.

scripts/install-deps.sh
=> Adapts install-deps.sh script for Manjaro Linux

Changelog.md, src/terminal/SixelParser.cpp
I never thought people would be using HSL sixel images, but seems like people are testing for it. So here it is.
=> Adds support for HSL colorspace in Sixel images.

Changelog.md, src/terminal/Screen.cpp
=> Fixes missing trival-line inflation in some corner case.

.clang-format, autogen.sh, src/terminal/Terminal.cpp, src/terminal/Terminal.h, src/terminal/Viewport.cpp, src/terminal/Viewport.h, src/terminal_renderer/Renderer.h
while working on QML, a view unrelated things got changes. this PR just keeps the big PR clean from unrelated stuff.
=> prep commits for QML port

Changelog.md, src/terminal/Capabilities.cpp
=> Adds lines#24 in terminfo file

.github/workflows/build.yml, scripts/install-deps.ps1, scripts/install-deps.sh, src/contour/Audio.cpp, src/contour/display/OpenGLRenderer.cpp
=> Bumping fmtlib and libunicode with it.

metainfo.xml, src/terminal/Terminal.cpp, src/terminal/ViInputHandler.h
=> Fixing selection magically deselecting when indicator status line was shown and the top page line was selected.

metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/ContourGuiApp.cpp, src/contour/ContourGuiApp.h, src/contour/contour.yml
=> Adds `live_config` reload configuration option.

.github/workflows/build.yml, .github/workflows/codechecker-analysis.yml, .github/workflows/release.yml, CMakeLists.txt, src/contour/CMakeLists.txt
=> revive Ubuntu 20.04 packaging

metainfo.xml, src/terminal/SixelParser.cpp, src/terminal/SixelParser_test.cpp
that's apparently been a bug. Thanks @jerch :)
=> [Sixel] Updating color palette must also update current pen color.

metainfo.xml, src/terminal/Cell.h, src/terminal/CellFlags.h, src/terminal/Functions.h, src/terminal/Screen.cpp, src/terminal/Screen.h, src/terminal/Screen_test.cpp, src/terminal/primitives.h
Closes #29 
Closes #30 
Closes #31
=> Adds VT sequence DECSCA, DECSEL, DECSED and DECSERA

metainfo.xml, src/contour/display/TerminalWidget.cpp, src/contour/display/TerminalWidget.h, src/terminal/Line.cpp, src/terminal/RenderBufferBuilder.cpp, src/terminal/RenderBufferBuilder.h, src/terminal/Screen.h, src/terminal/Terminal.cpp, src/terminal/Terminal.h
=> Visualize IME preedit text

metainfo.xml, src/terminal/Grid.cpp, src/terminal/Grid.h, src/terminal/Line.h
=> VT performance improvements for alternate-screen and custom-vertical-margin scroll-up 

src/terminal/Grid.h, src/terminal/Grid_test.cpp
- Added unit test to check line wrap and resize 
- Fixed historyLineCount function
=> [terminal] Fix historyLineCount

metainfo.xml, src/terminal/Parser.cpp, src/terminal/Parser.h, src/terminal/Sequencer.cpp
plus also allow bulk ground-state processing in alt screen.
=> Fixes ground-state infinite loop in corner case

metainfo.xml, src/terminal/Line.cpp, src/terminal/RenderBufferBuilder.cpp, src/terminal/Screen.cpp, src/terminal/Terminal.cpp, src/terminal_renderer/TextRenderer.cpp
Not generally broken but in some circumstances (such as in vim, where it's most annoying).
=> Fix wide char cursor placement

metainfo.xml, src/terminal/CellUtil.h, src/terminal/Process_unix.cpp, src/terminal/RenderBufferBuilder.cpp, src/terminal/RenderBufferBuilder.h, src/terminal/ViCommands.cpp, src/terminal/ViCommands.h, src/terminal/Viewport.h
=> various fixes

src/terminal/Grid.cpp, src/terminal/Grid_test.cpp, src/terminal/Line.cpp, src/terminal/Line_test.cpp
=> Preserve TrivialLineBuffer on grid resize

CODE_OF_CONDUCT.md
Seems like good to have one. :)
=> Adds an initial CODE_OF_CONDUCT.md

metainfo.xml, src/contour/helper.cpp
pretty simple, Alt+Backspace wasn't working on OS/X. This is fixing it.
=> Fixes Alt+Backspace on OS/X.

cmake/FilesystemResolver.cmake, scripts/install-deps.sh, src/crispy/stdfs.h
An attempt too deprecate the dependency on Boost libraries.
=> Enable use of stdfs on OS/X rather than depending on boost.

metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/contour.yml, src/terminal/Terminal.cpp, src/terminal/Terminal.h, src/terminal/TerminalState.h
Implements #889.
[contour-highlight-words.webm](https://user-images.githubusercontent.com/56763/205386478-26504e0c-2bd0-45f9-8850-dc70e94d8b74.webm)
=> Adds ability to highlight same words on double click.

src/contour/Config.cpp, src/contour/Config.h, src/contour/ContourGuiApp.cpp, src/contour/ContourGuiApp.h, src/contour/TerminalSession.cpp, src/crispy/ImageSize.h, src/terminal/CMakeLists.txt, src/terminal/primitives.h, src/terminal/pty/CMakeLists.txt, src/terminal/pty/ConPty.cpp, src/terminal/pty/ConPty.h, src/terminal/pty/LinuxPty.cpp, src/terminal/pty/LinuxPty.h, src/terminal/pty/MockPty.cpp, src/terminal/pty/MockPty.h, src/terminal/pty/MockViewPty.cpp, src/terminal/pty/MockViewPty.h, src/terminal/pty/PageSize.h, src/terminal/pty/Process.h, src/terminal/pty/Process_unix.cpp, src/terminal/pty/Process_win32.cpp, src/terminal/pty/Pty.cpp, src/terminal/pty/Pty.h, src/terminal/pty/UnixPty.cpp, src/terminal/pty/UnixPty.h
... to allow using the VT parser and PTY/Process API from the outside.
=> Some cmake related refactors

src/contour/Config.cpp, src/contour/Config.h, src/contour/display/Blur.cpp, src/contour/display/TerminalWidget.cpp
just a small one to reduce compiler noise.
=> Fixes compiler declaration warnings (-Wmissing-declarations).

src/vtbackend/Screen.cpp, src/vtbackend/Screen_test.cpp, src/vtbackend/Terminal.cpp
```markdown
Your issue description (body) goes here
```
see #897 
```markdown
```
Visually and added a test
No effect
=> Don't move cursor when setting top,bottom,left and right margins.

metainfo.xml, src/contour/Config.cpp, src/contour/contour.yml, src/vtbackend/ColorPalette.h, src/vtbackend/Terminal.cpp
just a minor feature to allow customizing the fg/bg colors for the indicator status line.
=> Adds color scheme key `indicator_statusline.foreground` and `indicator_statusline.background` to customize indicator statusline colors.

metainfo.xml, src/contour/display/TerminalWidget.cpp, src/vtbackend/Terminal.cpp
=> [vtbackend] Adds clock to indicator status line.

metainfo.xml, src/vtbackend/Terminal.cpp
=> Adds current viewport position in scrollback buffer to indicator status line

src/vtbackend/Terminal.cpp
```markdown
Your issue description (body) goes here
```
```markdown
```
=> Fixes applying wrong page size to main display.

metainfo.xml, src/vtbackend/Terminal.cpp
=> Fixes mouse selection not working while statusline is shown

src/contour/contour.yml
```markdown
Fixed some typos using aspell
```
```markdown
There were some obvious typos in the default config contour.yml> which were an easy fix.
```
- tried to run contour with the modified config, it ran just fine.
=> typo fixes in default config

scripts/install-deps.sh, src/contour/CMakeLists.txt
=> Fixes packaging for Qt6-based builds (e.g. affects Ubuntu 22.04).

metainfo.xml, src/contour/display/TerminalWidget.cpp
Reverts #918 - only until we've found a better fix for that :-)
=> Reverting #918 to fix rendering glitch.

metainfo.xml, src/text_shaper/font_locator.h, src/text_shaper/fontconfig_locator.cpp, src/text_shaper/open_shaper.cpp
Fixes loading TTC files that, up until now, did always load its first face rather the actually requested one.
Fixes #939.
=> Fixes loading TTC font files not honor which face to load within the collection (#939).

src/contour/Actions.h, src/contour/Config.cpp, src/contour/TerminalSession.cpp, src/text_shaper/fontconfig_locator.cpp, src/vtbackend/RenderBufferBuilder.cpp, src/vtbackend/RenderBufferBuilder.h, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h
=> prep-work for supporting different formats when copying selection to clipboard.

metainfo.xml, src/vtbackend/Screen.cpp
=> A linefeed should scollup with same graphics attributes as the cursor.

metainfo.xml, src/contour/Config.cpp
I wonder how that one went in and why I didn't notice earlier. 💀 
This should also fix the cwd issue we noticed on OS/X.
=> [contour] Fixes `initial_working_directory` setting being ignored.

.github/workflows/build.yml, .github/workflows/release.yml, cmake/DeployQt.cmake, src/contour/CMakeLists.txt, src/contour/Config.cpp
Slight continued push towards Qt6 by default on (almost) all platforms.
=> [CI] Build against Qt6 by default on Windows and OS/X.

src/contour/display/TerminalWidget.cpp, src/vtbackend/RenderBufferBuilder.cpp, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/Screen_test.cpp, src/vtbackend/Sequencer.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/TerminalState.cpp, src/vtbackend/TerminalState.h, src/vtbackend/ViCommands.cpp
generally seen as code cleanup and technical debt reduction.
=> refactors as prep-work to upcoming trace mode

metainfo.xml, src/vtrasterizer/CursorRenderer.cpp, src/vtrasterizer/DecorationRenderer.cpp
=> Fix rendering in some corner cases

scripts/install-deps.sh
=> Fix build on debian 11

metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/contour.yml
=> Add option to hide mouse while typing

metainfo.xml, src/vtbackend/ViCommands.cpp, src/vtbackend/ViCommands.h, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
Closes #974 but also implements much more that were missing or brings improvements to them.
=> Vi mode text object improvements.

metainfo.xml, src/contour/Config.cpp, src/contour/contour.yml, src/vtbackend/ColorPalette.h, src/vtbackend/RenderBufferBuilder.cpp, src/vtbackend/Terminal.cpp
=> Adds new config option `word_highlight_current` and `word_highlight_other`.

metainfo.xml, src/contour/Config.cpp, src/text_shaper/font.h, src/text_shaper/open_shaper.cpp
=> Adds ability to explicitly disable font features.

.github/workflows/build.yml, .github/workflows/release.yml, cmake/DeployQt.cmake
=> DeployQt.cmake: Applying a mini-maintenance-improvement

.github/workflows/build.yml, .github/workflows/release.yml
trying to get CI green (oops, sorry).
=> Fixing CI workflow for Ubuntu 22.04 packages

src/contour/Config.cpp
Closes #776
- Checked locally 
=> Make missing key message apear without debug log

src/contour/TerminalSession.cpp, src/vtbackend/Selector.cpp, src/vtbackend/Selector.h, src/vtbackend/Selector_test.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/ViCommands.cpp
This is all selection related and hyperlink hover related code simplifications.
=> Simplify mouse related event handling code for better code quality

src/contour/display/OpenGLRenderer.cpp, src/contour/display/OpenGLRenderer.h, src/contour/display/TerminalWidget.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtrasterizer/RenderTarget.h, src/vtrasterizer/Renderer.cpp, src/vtrasterizer/Renderer.h
performing some small'ish code cleanups.
=> some more code cleanups

metainfo.xml, src/contour/Config.cpp
=> [contour] Fixes abnormal termination on incomplete foreground/background color-pair specification.

metainfo.xml, src/contour/ContourApp.cpp, src/contour/resources.qrc, src/contour/shell-integration/shell-integration.tcsh
Thanks to @cqexbesd for the motivation to support shells I thought that only exist in museums nowadays :-D
=> [contour] Adds shell integration for tcsh shell.

src/contour/CMakeLists.txt
see the detailed build process, test information in https://github.com/contour-terminal/contour/issues/1042#issuecomment-1435881180
=> Fix build error with mimalloc

.gitignore
Adds entry for `CMakeUserPresets.json` file in `.gitignore`
=> add CMakeUserPresets.json in gitignore

metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/contour.yml, src/contour/display/TerminalWidget.cpp, src/contour/display/TerminalWidget.h, src/contour/helper.cpp, src/contour/helper.h, src/vtbackend/Screen.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h
=> Adds `profiles.*.permissions.display_host_writable_statusline` to allow the user to intervene in `DECSSDT`

.github/workflows/build.yml, .github/workflows/codechecker-analysis.yml, .github/workflows/external_tests.yml, metainfo.xml, src/vtbackend/InputGenerator.cpp, src/vtbackend/Selector.cpp, src/vtbackend/Terminal.cpp
=> [vtbackend] Fixes selecting a single character not working easily

metainfo.xml, src/contour/display/ShaderConfig.cpp
Closes https://github.com/contour-terminal/contour/issues/715
=> Create separate category for shader log

metainfo.xml, src/contour/Config.cpp, src/contour/contour.yml, src/vtbackend/ColorPalette.h, src/vtbackend/RenderBufferBuilder.cpp
=> Allow customizing the IME (input method editor) region

.github/workflows/build.yml, .github/workflows/external_tests.yml, .github/workflows/release.yml, scripts/ci/notcurses-install-deps.sh
seems like we were missing .dmg files in the list of generated package files on master or PR CI runs. :)
=> Revive packaging and uploading DMG package for OS/X.

metainfo.xml, src/contour/contour.yml, src/vtbackend/Screen.cpp
=> Changes `DECSSDT 2` permission check to always apply.

src/vtbackend/Terminal.cpp
=> Fixes accidental creation of text selection object (caused by PR #1075)

README.md
=> Add installation section and move requierements and configuration sections in Readme file

src/vtpty/Process_unix.cpp, src/vtpty/Process_win32.cpp
=> Use default shell if can not spawn user defined

metainfo.xml, src/vtbackend/Terminal.cpp
=> Fixes statusline being misplaced after resize when being in alt screen

metainfo.xml, src/vtbackend/ViInputHandler.cpp
=> Model mode: Adds handling of `Home` and `End` keys

.github/workflows/build.yml, .github/workflows/release.yml, metainfo.xml, src/vtbackend/Terminal.cpp, src/vtbackend/ViCommands.cpp, src/vtbackend/ViInputHandler.cpp, vcpkg.json
this is a little UX improvement
=> Reuse existing search term when re-entering search term editor

scripts/install-deps.sh
=> Enable libutempter to build as embed package

.github/archlinux/Dockerfile
This is official docker image that works
=> Fix archlinux docker image

.github/fedora/contour.spec
Fix fedora github actions build
=> Change path of CONTRIBUTING.md

.github/workflows/build.yml, docs/internals/index.md, docs/vt-extensions/buffer-capture.md, docs/vt-extensions/clickable-links.md, docs/vt-extensions/font-settings.md, docs/vt-extensions/index.md, docs/vt-extensions/synchronized-output.md, docs/vt-extensions/vertical-line-marks.md, mkdocs.yml
general update on internals documentation and first steps on documenting VT extensions.
=> [docs] Add preliminary VT extensions documentation and a little cleanup wrt internals

.github/workflows/build.yml, scripts/install-deps.sh
Add fedora rawhide in github action to be aware of issues with dependencies as early as possible
Closes https://github.com/contour-terminal/contour/issues/1127
=> Add rawhide fedora into github actions

.github/workflows/build.yml, cmake/DeployQt.cmake, src/contour/CMakeLists.txt
Possibly a requirement for #761.
https://github.com/WerWolv/ImHex/blob/fdd2e1fcde1158164090aacf370b509ffd199593/cmake/modules/PostprocessBundle.cmake
This is a good file to learn from
=> [CMake] contour: run macdeployqt for packaging on OS/X

src/contour/TerminalSession.h, src/contour/ui.template/Terminal.qml.in
=> Fix scrollbar hidden state

metainfo.xml, src/contour/display/TerminalWidget.cpp, src/contour/display/TerminalWidget.h
Fixes #1153, is this the correct way to solve this in QML world?
=> Fixes `show_title_bar` config option

src/contour/ui.template/Terminal.qml.in
second attempt to fix it. meh.
=> Fixing scrollbar configured to be hidden, again. This time by also setting ScrollBar.policy

src/vtpty/CMakeLists.txt, src/vtpty/UnixPty.cpp, src/vtpty/UnixPty.h, src/vtpty/UnixUtils.cpp, src/vtpty/UnixUtils.h
=> Move UnixPipe to UnixUtils.h and also add UnixUtils.cpp

src/contour/Config.cpp, src/contour/Config.h, src/contour/ContourApp.cpp, src/contour/ContourGuiApp.cpp, src/contour/ContourGuiApp.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/display/TerminalWidget.cpp, src/crispy/App.cpp, src/crispy/App.h, src/crispy/CMakeLists.txt, src/crispy/stdfs.h, src/crispy/utils.h, src/vtbackend/ColorPalette.h, src/vtbackend/Terminal.cpp, src/vtpty/Process.h, src/vtpty/Process_unix.cpp, src/vtpty/Process_win32.cpp, src/vtrasterizer/RenderTarget.h
=> Drop <crispy/stdfs.h> in favor of <filesystem>

README.md, docs/install.md
Update link to AUR package so users download package from Release package
=> Update link to point  to our aur file

.github/workflows/build.yml
Adds check for build action to check deb package installation
=> Action to check package for Ubuntu

src/crispy/utils.h, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/Sequence.h, src/vtbackend/Sequencer.cpp, src/vtbackend/Sequencer.h, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/bench-headless.cpp, src/vtparser/Parser-impl.h, src/vtparser/Parser.h, src/vtparser/ParserEvents.h, src/vtparser/Parser_test.cpp
make (textual | VT sequence) trace logging more usable
=> Have text trace logging a little bit more convenient

src/vtbackend/Line.h
Small update of variant use inside `Line`
=> Small refactor of variant access for line

metainfo.xml, src/vtbackend/Functions.h, src/vtbackend/Grid.h, src/vtbackend/MockTerm.h, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/Screen_test.cpp, src/vtparser/Parser-impl.h, src/vtparser/Parser.h
This was about time to get fixed.
Refs #1201 
While it addresses the issues mentioned by j4james in #1201, it sadly won't fix the tmux issue just yet. Maybe in the next hunting session :)
=> Various cursor/margin related fixes and minor QA improvements

metainfo.xml, src/vtbackend/Terminal.cpp
random improvements....
- Terminal: Add percentage value to Indicator Statusline
- Terminal: Fix mouse move events not being reported (even when requested)
=> random improvements - Add percentage value to Indicator Statusline & mouse move event fix

src/contour/display/TerminalWidget.cpp, src/contour/display/TerminalWidget.h
Update  OSC 888 implementation to handle QML
=> Fix OSC 888 after qml merge

metainfo.xml, src/crispy/read_selector.h, src/vtpty/UnixPty.cpp
Trying to finally and actually fix the terminal terminating early on idle input.
=> Finish the fix of idle terminal sessions terminating early

metainfo.xml, src/crispy/read_selector.h, src/text_shaper/open_shaper.cpp, src/vtbackend/Terminal.cpp, src/vtpty/ConPty.cpp, src/vtpty/ConPty.h, src/vtpty/MockPty.cpp, src/vtpty/MockPty.h, src/vtpty/MockViewPty.cpp, src/vtpty/MockViewPty.h, src/vtpty/Process.h, src/vtpty/Pty.h, src/vtpty/UnixPty.cpp, src/vtpty/UnixPty.h, src/vtrasterizer/TextRenderer.cpp
=> Fixes Emoji rendering being too small on OS/X

src/crispy/read_selector.h, src/vtpty/UnixPty.cpp
Fixing my brain damage from last night
=> Pty::read() fix

src/text_shaper/open_shaper.cpp
This PR fixes bug in bad access of `face->available_sizes[0]` because number_of_elements can be zero
=> Check size of available_sizes to not get SEGV

metainfo.xml, src/contour/TerminalSession.cpp
When closing from window manager GUI will disappear but process was still alive, this PR fix this behavior
=> Fix contour close

scripts/install-deps.sh
closes https://github.com/contour-terminal/contour/issues/1238
=> Move qml package to common list

src/vtbackend/MockTerm.h, src/vtbackend/Screen.cpp, src/vtbackend/Screen_test.cpp, src/vtbackend/Terminal.cpp
test are always good.
I should have done that in the prior PR, so i could have caught, that i was missing a line. :(
=> Adds test case for DSR (Color Palette Updated) and fix missing reverse translation

metainfo.xml, src/contour/helper.cpp, src/vtbackend/InputGenerator.cpp, src/vtbackend/InputGenerator.h
=> Adds support vor horizontal mouse scrolling event reporting sequences

.github/workflows/build.yml
During GUI action we are trying to download artifacts that are not created to that time. 
This PR attempts to fix it
=> Add dependency for gui action

src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/display/TerminalWidget.cpp, src/contour/display/TerminalWidget.h, src/contour/helper.cpp, src/contour/helper.h, src/vtbackend/InputGenerator.cpp, src/vtbackend/InputGenerator.h, src/vtbackend/InputGenerator_test.cpp, src/vtbackend/MockTerm.h, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/Terminal_test.cpp, src/vtbackend/ViCommands_test.cpp
Modularize InputGenerator's keyboard input handling into its own special class.
This should ideally improve readability/maintainability of the (keyboard) input generating logic.
=> Refactor keyboard input handling

src/contour/Actions.h, src/vtbackend/Terminal.cpp, src/vtbackend/Viewport.cpp, src/vtbackend/Viewport.h
Closes https://github.com/contour-terminal/contour/issues/1222
=> Initial atempts to fix bug with current screen being indicator status

metainfo.xml, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/Viewport.cpp, src/vtbackend/Viewport.h
=> [vtbackend] Moves the vi-like cursor with the viewport when scrolling up/down

metainfo.xml, src/vtbackend/CellFlags.h, src/vtbackend/GraphicsAttributes.h, src/vtbackend/Grid.cpp, src/vtbackend/Line.cpp, src/vtbackend/Screen.cpp, src/vtbackend/Screen_test.cpp, src/vtbackend/cell/SimpleCell.h
closes #1268 
i mean, this is currently only the test case added. fix comming next.
=> Fix printing over 2nd cell in wide character should delete wide character

.github/workflows/build.yml
=> Split CI artifacts per OS-release

src/contour/ui.template/Terminal.qml.in
Fix opacity of background image when blur is enabled
To get desired opacity we insert additional rectangle in front of blur with opacity matching background image
=> Fix opacity of background image when blur is enabled

scripts/install-deps.sh, src/crispy/read_selector.h
Fix build with g++ (GCC) 13.2.1 and range, as well as some errors from gentoo
=> Some minor fixes and updates

src/contour/TerminalSession.cpp, src/crispy/read_selector.h, src/vtbackend/Terminal.cpp, src/vtpty/UnixPty.cpp
=> Fix PTY reads on MacOS and FreeBSD

src/vtbackend/SixelParser.cpp
=> Fix error with out of bounds access

src/crispy/CMakeLists.txt, src/crispy/file_descriptor.h, src/crispy/read_selector.h, src/vtpty/UnixPty.cpp, src/vtpty/UnixPty.h
the idea is adopted from what I once coded for the x0 HTTP server, in order to provide a safe resource for file descriptors.
=> Add safe file descriptor API

.github/workflows/changelog.yml, src/contour/ContourGuiApp.cpp, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/display/CMakeLists.txt, src/contour/display/TerminalDisplay.cpp, src/contour/display/TerminalDisplay.h, src/contour/helper.cpp
=> Rename TerminalWidget to TerminalDisplay

.github/workflows/changelog.yml, metainfo.xml, src/contour/TerminalSession.cpp, src/contour/TerminalSessionManager.cpp, src/contour/display/OpenGLRenderer.cpp, src/contour/display/OpenGLRenderer.h, src/contour/helper.h
=> Fix some Qt/OpenGL related problems

src/contour/TerminalSession.cpp
Closes https://github.com/contour-terminal/contour/issues/1303
=> Dont force redraw on hard reset for status line

docs/vt-extensions/csi-u-extended-keyboard-protocol.md
=> fixed typo error in csi-u-extended-keyboard-protocol.md

src/vtpty/ConPty.cpp
we didn't do that yet, but it helps when investigating PTY I/O issues on Windows.
=> add logging to ConPTY I/O

docs/install.md
Addresses the feedback from https://github.com/contour-terminal/contour/issues/393#issuecomment-1783952542
=> [docs] Adds URL to release page for windows-install section

src/contour/ui.template/Terminal.qml.in
Fix scroll freeze due to error in conversion from float to int while 532.9999 -> 532
=> Fix scroll freeze

src/vtbackend/Image.cpp, src/vtbackend/Image.h, src/vtbackend/Screen.cpp
=> Minor cleanup on how to instanciate a RasterizedImage

src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/ui.template/Terminal.qml.in, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/Terminal.cpp
Closes #1351
- no changelog needed, because bug was introduced after last release
=> Fixes DECSSDT

.github/workflows/build.yml, README.md, docs/internals/text-stack.md
Use https://github.com/TechWiz-3/linksafe to verify that links are working
Waiting for : https://github.com/TechWiz-3/linksafe/issues/12
=> Add github action to check links in the documentation and root

.github/workflows/build.yml, src/contour/ContourApp.cpp, src/crispy/Intrinsics.h, src/vtbackend/Charset.cpp, src/vtrasterizer/DecorationRenderer.cpp
=> Update linksafe action

src/vtpty/Process_unix.cpp
=> [Process] Avoid throwing an exception if waitpid() failed

metainfo.xml, src/vtbackend/Screen.cpp
=> Fix VT sequence XTWINOPS to not assert and terminate

.github/workflows/build.yml, metainfo.xml, scripts/ci-set-vars.ps1, scripts/ci-set-vars.sh, scripts/install-deps.sh, src/contour/helper.cpp
=> Release 0.4.0

metainfo.xml, src/contour/Config.cpp, src/vtbackend/Capabilities.cpp
Please use `contour` terminfo instead
=> Remove `contour-latest` terminfo file.

docs/configuration/profiles.md, metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/contour.yml, src/contour/display/TerminalDisplay.cpp, src/contour/display/TerminalDisplay.h, src/contour/helper.cpp, src/contour/helper.h, src/contour/ui.template/main.qml.in
=> Add config option `profiles.*.margins` to allow customizing the horizontal / vertical margins

docs/configuration/colors.md, metainfo.xml, src/contour/Config.cpp, src/vtbackend/ColorPalette.cpp, src/vtbackend/ColorPalette.h, test/dimmed-bold-bright-text.sh
=> Add config option to customize default bold/bright and dimmed foreground colors

.github/workflows/build.yml
=> Ensure next release will include ZIP package for Windows

src/contour/ui.template/Terminal.qml.in
Fixes mistake with rounding of scrollbar position and loop dependency between scrollbar position and offset
=> Properly manage scrollbar and offset

metainfo.xml, scripts/install-deps.sh, src/contour/display/CMakeLists.txt
Refs #1397.
@marenz, would you mind reviewing? What do you think I can improve?
=> Fixes `scripts/install-deps.sh` for openSuSE (Tumbleweed) to install the correct dependencies

metainfo.xml, scripts/install-deps.sh, src/contour/CMakeLists.txt, src/contour/helper.cpp
refs #1397 
this PR fixes some missing dependencies for .deb packages
=> Fixes missing dependencies for release .deb packages

metainfo.xml, src/vtrasterizer/TextRenderer.cpp
=> Fix `...` programming ligature rendering issue

src/vtrasterizer/TextRenderer.cpp, src/vtrasterizer/TextRenderer.h
FYI: @Marenz just in case if that was the reason for your rollback :)
=> Fixes text render bug that was just introduced

.github/workflows/build.yml, autogen.sh, metainfo.xml, src/contour/CMakeLists.txt
Finally!
Refs original idea of #276.
=> Digitally sign MacOS release binaries using a valid Apple ID

.github/workflows/build.yml, scripts/install-deps.sh, src/vtrasterizer/CMakeLists.txt
=> Fix FreeBSD github action

metainfo.xml, src/contour/Config.cpp, src/contour/Config.h
=> Set history lines default to 1000 rather than 0.

cmake/ContourThirdParties.cmake, scripts/install-deps.ps1, scripts/install-deps.sh, src/contour/contour.yml
=> Bump boxed-cpp version and ensure it's always the correct one being built against

metainfo.xml, src/contour/TerminalSession.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h
Fixes bug introduced in https://github.com/contour-terminal/contour/pull/1450
=> Fix dead lock of terminal

metainfo.xml
sadly again, due to deadlock we've just found.
=> Release 0.4.3

.github/workflows/build.yml, metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/ConfigDocumentation.h, src/contour/ContourGuiApp.cpp, src/contour/ContourGuiApp.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/TerminalSessionManager.cpp, src/contour/display/TerminalDisplay.cpp, src/contour/display/TerminalDisplay.h, src/contour/helper.cpp, src/contour/helper.h, src/text_shaper/font.h, src/vtbackend/ColorPalette.cpp, src/vtbackend/ColorPalette.h, src/vtbackend/Settings.h
Closes https://github.com/contour-terminal/contour/issues/1292
Refs https://github.com/contour-terminal/contour/issues/1282
=> Refactor configuration loading

src/contour/Config.cpp, src/contour/Config.h
Closes https://github.com/contour-terminal/contour/issues/1475
=> Ammendum to config refactor

src/contour/Config.h
Fix generation of new config file
=> Fix format of mods during config generation

docs/configuration/indicator-statusline.md, metainfo.xml, mkdocs.yml, src/contour/Config.cpp, src/contour/Config.h, src/contour/ConfigDocumentation.h, src/contour/TerminalSession.cpp, src/crispy/CMakeLists.txt, src/crispy/flags.h, src/crispy/interpolated_string.cpp, src/crispy/interpolated_string.h, src/crispy/interpolated_string_test.cpp, src/vtbackend/CMakeLists.txt, src/vtbackend/Color.cpp, src/vtbackend/Color.h, src/vtbackend/ColorPalette.h, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/Sequencer.cpp, src/vtbackend/Sequencer.h, src/vtbackend/Settings.h, src/vtbackend/StatusLineBuilder.cpp, src/vtbackend/StatusLineBuilder.h, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h
=> Add customizable statusline

metainfo.xml, src/contour/TerminalSession.cpp
Closes https://github.com/contour-terminal/contour/issues/1472
=> Fix key bindings and search prompt

.github/workflows/build.yml, docs/configuration/index.md, metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/ConfigDocumentation.h, src/contour/ContourGuiApp.cpp, src/contour/TerminalSession.cpp, src/contour/contour.yml
Closes https://github.com/contour-terminal/contour/issues/1460
=> Implement early exit threshold config entry

metainfo.xml, src/contour/ContourApp.cpp, src/contour/resources.qrc, src/contour/shell-integration/shell-integration.bash
This PR adds bash integration script to contour and closes https://github.com/contour-terminal/contour/issues/163
=> Add bash integration

metainfo.xml, src/contour/TerminalSession.h, src/contour/ui.template/Terminal.qml.in
Closes https://github.com/contour-terminal/contour/issues/1515
=> Fix bell after new window creation

metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/ConfigDocumentation.h, src/contour/TerminalSession.cpp, src/contour/contour.yml, src/vtbackend/Settings.h, src/vtbackend/ViInputHandler.cpp, src/vtbackend/ViInputHandler.h
This PR adds config entry to allow user to configure behavior on search exit,
so user can change in which mode to switch after exit from search
=> Add config entry to exit search mode into insert or normal

src/crispy/BufferObject.h, src/vtbackend/CellUtil.h, src/vtbackend/Grid.cpp, src/vtbackend/Grid.h, src/vtbackend/Line.cpp, src/vtbackend/Line.h, src/vtbackend/RenderBufferBuilder.cpp, src/vtbackend/RenderBufferBuilder.h, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h, src/vtbackend/VTWriter.cpp, src/vtbackend/VTWriter.h, src/vtbackend/cell/CellConcept.h, src/vtparser/Parser-impl.h, src/vtparser/Parser.h
Well, compiling right now. But it's always good to have a concept in the back :)
=> Make more use of C++20 concepts for better compiler error diagnostics

src/vtpty/Process_unix.cpp, src/vtpty/UnixPty.cpp
;-(
refs #1509 
refs https://github.com/flathub/org.contourterminal.Contour/pull/16
=> Revive fixes made for Flatpak, accidentally dropped in PR #1168

.github/workflows/docs.yml, mkdocs.yml, scripts/extract-changelog-from-metainfo.py
too bad, we only see this when we have merged to master 🤔
=> Add auto-generated release-notes page to website

src/contour/TerminalSession.h, src/contour/ui.template/Terminal.qml.in
=> Fix qml warnings

.github/workflows/docs.yml, .gitignore, docs/stylesheets/extra.css, mkdocs.yml, src/contour/ContourApp.cpp, src/contour/ContourApp.h, src/crispy/escape.h, src/vtbackend/Functions.cpp, src/vtbackend/Functions.h, src/vtbackend/Functions_test.cpp, src/vtbackend/Screen.cpp, src/vtbackend/Screen.h, src/vtbackend/Sequence.h, src/vtbackend/Terminal.h
Generate vt sequence documentation for web page
=> Create VT extensions list for documentation

.github/workflows/docs.yml
For some weird reason action on master for docs is broken, this PR attempts to fix it
=> Fix docs creation

.github/workflows/build.yml, metainfo.xml
let's see if we can make it :)
=> [Github CI] Update macOS job to macos-14

metainfo.xml, src/contour/ContourGuiApp.cpp, src/crispy/App.cpp
Closes https://github.com/contour-terminal/contour/issues/629
=> Handle different arguments for contour executable

metainfo.xml, src/contour/TerminalSession.cpp, src/vtbackend/Terminal.cpp, src/vtbackend/Terminal.h
Closes https://github.com/contour-terminal/contour/issues/783
=> Add key binding disabled indicator

.github/workflows/docs.yml, docs/configuration/key-mapping.md, src/contour/Actions.h, src/contour/Config.cpp, src/contour/ConfigDocumentation.h, src/contour/ContourApp.cpp, src/contour/ContourApp.h, src/vtbackend/Color.cpp
Closes https://github.com/contour-terminal/contour/issues/1442
=> Add key map documentation generation

src/vtbackend/Terminal.cpp, src/vtbackend/ViCommands.cpp
Fix https://github.com/contour-terminal/contour/pull/1544
=> Fix scrolling jump when go to normal mode

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/general.md, .github/ci-ppa/dput.cf, .github/mock-font-locator.yml, .github/workflows/codeql-analysis.yml.disabled, CODE_OF_CONDUCT.md, autogen.sh, examples/CMakeLists.txt, metainfo.xml, scripts/ci-set-vars.sh, src/crispy/CMakeLists.txt, test/origin-mode-and-margins.sh
=> Fix editorconfig

metainfo.xml, src/crispy/utils.h, src/vtbackend/CellUtil.h, src/vtbackend/Grid.h, src/vtbackend/Line.h, src/vtbackend/RenderBufferBuilder.cpp, src/vtbackend/Screen.cpp, src/vtbackend/cell/CellConcept.h, src/vtbackend/cell/CompactCell.h, src/vtbackend/cell/SimpleCell.h
Refs https://github.com/contour-terminal/contour/issues/1410
=> Implement case-insesitive smart search

metainfo.xml
Closes  https://github.com/contour-terminal/contour/issues/916 in https://github.com/contour-terminal/contour/commit/83c02f51cf447766c5a942b171dfb17a0d6f3ab6
=> Add metainfo entry for the bug fix

metainfo.xml, src/vtbackend/CellUtil.h, src/vtbackend/Grid_test.cpp, src/vtbackend/Line.cpp
PR fixes bug when spaces will be deleted on resize
=> Preserve spaces on resize

src/contour/Config.h, src/vtpty/Process_unix.cpp
Update default config and change default font on MacOs
=> update default config and restrict font selection on macos

.github/workflows/build.yml, scripts/ci/notcurses-install-deps.sh
PR fixes notcurses action that got broken recently 
Actions where failing due to bad artifact for installed notcurses, i updated  GUI test action to build notcurses locally and combine few tests from notcurses-demo
=> Fix notcurses gihub action

.github/workflows/build.yml
Issue with packaging appears from cmake
=> Fix windows packaging

src/contour/Config.cpp, src/contour/Config.h
Inheritance of terminal profiles was broken, this PR fixes it
=> Fix inheritance of terminal profiles

metainfo.xml, src/contour/contour.desktop
Closes https://github.com/contour-terminal/contour/issues/1570
=> Add xdg-terminal-exec support

scripts/install-deps.ps1, scripts/install-deps.sh, src/vtbackend/CellUtil.h, src/vtbackend/cell/CompactCell.h, src/vtbackend/cell/SimpleCell.h
=> Update to latest libunicode to 0.5.0

.github/workflows/build.yml, metainfo.xml
=> Release 0.5.0

.github/appimage/AppImageBuilder.yml, .github/appimage/Dockerfile, .github/workflows/build.yml
Closes https://github.com/contour-terminal/contour/issues/1595
=> Use appimage-builder to create appimage

.github/appimage/AppImageBuilder.yml, .github/appimage/Dockerfile, .github/workflows/build.yml, .github/workflows/changelog.yml, .github/workflows/codechecker-analysis.yml, metainfo.xml, scripts/install-deps.sh
in the hope of making the life easier for us :)
=> Overall old Ubuntu 22.04 removals. We only want to support latest LTS  of Ubuntu

metainfo.xml, src/contour/Config.cpp
=> Load rendered backend from config

src/contour/Audio.cpp
Closes https://github.com/contour-terminal/contour/issues/1613
=> Fix header in audio.cpp file

.github/workflows/docs.yml
fix documentation github action
After switch to std::format we need a more recent compiler
=> Fix docs github action

metainfo.xml, src/vtbackend/ViInputHandler.cpp
Refs https://github.com/contour-terminal/contour/issues/1604
=> Exit normal mode with Escape

docs/configuration/profiles.md, metainfo.xml, src/contour/Config.cpp, src/contour/Config.h, src/contour/ConfigDocumentation.h, src/contour/TerminalSession.cpp, src/vtbackend/Settings.h, src/vtbackend/ViCommands.cpp
Refs https://github.com/contour-terminal/contour/issues/1604
=> Add insert_after_yank config option

src/contour/Config.h
=> [contour] Change default tabs position on statusbar to the left

.github/workflows/build.yml
Closes https://github.com/contour-terminal/contour/issues/1597 
Closes https://github.com/contour-terminal/contour/issues/1636
Adds github action to build x86 executable for macOS
=> Add macOS x86 action

metainfo.xml, src/contour/Actions.cpp, src/contour/Actions.h, src/contour/ConfigDocumentation.h, src/contour/TerminalSession.cpp, src/contour/TerminalSession.h, src/contour/display/TerminalDisplay.cpp, src/contour/display/TerminalDisplay.h
Closes https://github.com/contour-terminal/contour/issues/210
=> Implement SaveScreenshot and CopyScreenshot action

src/vtbackend/Terminal.cpp
Fixes positioning of middle segment in the status line
=> Position middle segment of status line properly

README.md
Closes https://github.com/contour-terminal/contour/issues/1649
=> Update readme with no macos specific version requirement

cmake/presets/os-windows.json, src/crispy/StrongHash.h
Closes https://github.com/contour-terminal/contour/issues/1654
=> Fix clang-19 and libc++ compilation @paparodeo

.github/static/DockerQt, src/vtpty/SshSession.h
Update static build docker file to use newer qt version and fix compilation issue
=> Update and fix static build

metainfo.xml, src/vtbackend/Screen.cpp, src/vtbackend/Screen_test.cpp
Closes https://github.com/contour-terminal/contour/issues/1664
=> Fix bug with call of DECFRA out of bounds

src/contour/Config.h
Small fix of the signature for the format function
=> Fix signature for format function for ExecInfo type

metainfo.xml, src/contour/ContourApp.cpp
thx to ptr1337 and @vnepogodin on Discord :)
=> [contour] Do not abort when failing to create `XDG_STATE_HOME/contour/crash` directory

docs/vt-extensions/color-palette-update-notifications.md
=> color-palette-update-notifications.md: fix typo

metainfo.xml, src/contour/display/TerminalDisplay.cpp
=> Fixes startup crash when window is not yet fully initialized

.github/workflows/build.yml
=> Add arm runner to the ubuntu matrix

.github/actions/spelling/allow/allow.txt, .github/actions/spelling/allow/names.txt, .github/workflows/build.yml, src/text_shaper/shaper.cpp
refactor function and update include for range-v3
=> Refactor shaper

.github/workflows/build.yml, src/crispy/StackTrace.cpp, src/crispy/utils.h, src/text_shaper/shaper.cpp, src/vtbackend/Capabilities.h, src/vtbackend/Color.h, src/vtbackend/SequenceBuilder.h, src/vtbackend/ViInputHandler.cpp, src/vtbackend/bench-headless.cpp, src/vtparser/Parser-impl.h, src/vtrasterizer/DecorationRenderer.cpp, src/vtrasterizer/Pixmap.h, src/vtrasterizer/TextureAtlas.h
Update github action to clang 20
=> Update clang version

docs/vt-extensions/color-palette-update-notifications.md
Track Dark and Light Mode detection implementation status for VTE
=> color-palette-update-notifications.md: add VTE

docs/vt-extensions/color-palette-update-notifications.md
Sorry, didn't notice initially..
=> color-palette-update-notifications.md: fix non-clickable Vim link

docs/vt-extensions/color-palette-update-notifications.md
Track Dark and Light Mode detection implementation status for Nushell.
=> color-palette-update-notifications.md: add Nushell

.github/actions/spelling/allow/allow.txt, src/vtbackend/Screen.cpp, src/vtbackend/Sequence.h, src/vtbackend/VTType.cpp, src/vtbackend/VTType.h
Closes https://github.com/contour-terminal/contour/issues/1765
Thanks a lot @j4james for figuring this out
=> Copy Extension (OSC 52) update 

metainfo.xml, src/contour/helper.h, src/vtbackend/InputGenerator.cpp, src/vtbackend/InputGenerator.h
=> [vtbackend] InputGenerator: Fixes NumLock key handling
